First, we need to set up the environment with the necessary Hugging Face libraries, including bitsandbytes for memory-efficient model loading and llmlingua for the base token importance.

In [1]:
!pip install -q transformers datasets accelerate bitsandbytes torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 18.3 MB/s eta 0:00:00

We will load the TweetEval dataset, the RoBERTa classifier, and the Qwen2.5 generator.

In [2]:
import torch
import numpy as np
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    AutoModelForSequenceClassification, BitsAndBytesConfig
)
from datasets import load_dataset

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# ── Dataset ───────────────────────────────────────────────────────────────
print("Loading dataset...")
dataset   = load_dataset("tweet_eval", "irony")
test_data = dataset["test"]

# ── RoBERTa irony classifier ──────────────────────────────────────────────
print("Loading RoBERTa classifier...")
roberta_name  = "cardiffnlp/twitter-roberta-base-irony"
rob_tokenizer = AutoTokenizer.from_pretrained(roberta_name)
rob_model     = AutoModelForSequenceClassification.from_pretrained(
    roberta_name
).to(device)

# ── Qwen 2.5-3B (4-bit) ──────────────────────────────────────────────────
print("Loading Qwen2.5-3B (4-bit quantised)...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)
qwen_name      = "Qwen/Qwen2.5-3B-Instruct"
qwen_tokenizer = AutoTokenizer.from_pretrained(qwen_name)
qwen_model     = AutoModelForCausalLM.from_pretrained(
    qwen_name,
    device_map="auto",
    quantization_config=bnb_config
)
print("All models loaded.")

Device: cuda
Loading dataset...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

irony/train-00000-of-00001.parquet:   0%|          | 0.00/183k [00:00<?, ?B/s]

irony/test-00000-of-00001.parquet:   0%|          | 0.00/54.0k [00:00<?, ?B/s]

irony/validation-00000-of-00001.parquet:   0%|          | 0.00/61.1k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2862 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/784 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/955 [00:00<?, ? examples/s]

Loading RoBERTa classifier...

config.json:   0%|          | 0.00/705 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-irony
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading Qwen2.5-3B (4-bit quantised)...

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

All models loaded.

Preprocessing

In [5]:
import torch.nn.functional as F
import nltk, re
from nltk.corpus import stopwords

nltk.download('stopwords', quiet=True)

STOP_WORDS = set(stopwords.words('english'))

# ── Prompt template (used by both baselines) ──────────────────────────────
STRUCTURED_PROMPT = (
    "Analyze whether the following tweet is ironic or non-ironic. "
    "Think step-by-step, then end your response with EXACTLY one of:\n"
    "Verdict: IRONIC\n"
    "Verdict: NON-IRONIC\n\n"
    "Tweet: '{tweet}'"
)


def classify_tweet(tweet_text):
    """
    Classifies the raw tweet with RoBERTa.
    Returns (predicted_label, p_ironic).
    """
    inputs = rob_tokenizer(
        tweet_text, return_tensors="pt",
        truncation=True, max_length=128
    ).to(device)
    with torch.no_grad():
        logits = rob_model(**inputs).logits
    probs      = F.softmax(logits, dim=-1).squeeze().cpu()
    p_ironic   = probs[1].item()
    prediction = int(p_ironic >= 0.5)
    return prediction, p_ironic


def vanilla_compress(cot_text, gamma=0.50):
    """
    Trims cot_text to (1 - gamma) of its original word count.
    Drops stopwords first, then shortest remaining words.
    No gradient sensitivity, no critical-token protection.
    Returns the compressed string.
    """
    words         = cot_text.split()
    target_length = max(5, int(len(words) * (1.0 - gamma)))

    scored = []
    for idx, word in enumerate(words):
        clean = word.lower().strip(".,!?\"'")
        score = 1 if (clean in STOP_WORDS or len(clean) < 3) else 10
        scored.append((idx, word, score))

    scored.sort(key=lambda x: x[2], reverse=True)
    kept = sorted(scored[:target_length], key=lambda x: x[0])
    return " ".join(w[1] for w in kept)


def extract_structured_cot_signal(cot_text):
    """
    Extracts the verdict (IRONIC/NON-IRONIC) from the CoT text.
    Returns 1.0 for IRONIC, 0.0 for NON-IRONIC, and 0.5 if no clear verdict is found.
    """
    if "Verdict: IRONIC" in cot_text:
        return 1.0
    elif "Verdict: NON-IRONIC" in cot_text:
        return 0.0
    else:
        return 0.5 # Ambiguous or verdict not found


print("✅ Helpers ready: classify_tweet | vanilla_compress | STRUCTURED_PROMPT | extract_structured_cot_signal")

✅ Helpers ready: classify_tweet | vanilla_compress | STRUCTURED_PROMPT | extract_structured_cot_signal

Uncompressed CoT

In [6]:
import pandas as pd
from IPython.display import display

# ════════════════════════════════════════════════════════════════════════════
# BASELINE 1 — Uncompressed CoT  (γ = 0.00)
#
# What this measures:
#   • Accuracy  : Verdict extracted from Qwen's FULL, uncompressed CoT via
#                 extract_structured_cot_signal. Because the complete reasoning
#                 chain is intact, Qwen's "Verdict:" line survives and the
#                 parser returns a clean 0.0 / 1.0 signal.
#   • Avg tokens: the full word count of every generated CoT.
#
# This reflects Qwen's actual reasoning ability on irony detection — a genuine
# upper-bound CoT baseline before any compression is applied.
# ════════════════════════════════════════════════════════════════════════════

NUM_SAMPLES = 100

results_list        = []
correct_predictions = 0
total_cot_tokens    = 0

print("🚀 BASELINE 1 — Uncompressed CoT  (γ = 0.00)")
print(f"   N = {NUM_SAMPLES}\n")

for i in range(NUM_SAMPLES):
    sample_tweet = test_data[i]["text"]
    true_label   = test_data[i]["label"]

    # ── Generate full CoT ─────────────────────────────────────────────────
    prompt = STRUCTURED_PROMPT.format(tweet=sample_tweet)
    inputs = qwen_tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = qwen_model.generate(
            **inputs,
            max_new_tokens=120
        )

    generated_ids = outputs[0][inputs["input_ids"].shape[1]:]
    cot_text      = qwen_tokenizer.decode(generated_ids, skip_special_tokens=True)
    cot_len       = len(cot_text.split())
    total_cot_tokens += cot_len

    # ── Extract verdict directly from Qwen's full CoT ─────────────────────
    # The uncompressed reasoning is intact, so the "Verdict:" line is present
    # and extract_structured_cot_signal returns a hard 0.0 or 1.0 signal.
    cot_signal = extract_structured_cot_signal(cot_text)
    prediction = int(cot_signal >= 0.5)   # 0.5 (ambiguous) → non-ironic (0)

    is_correct = (prediction == true_label)
    if is_correct:
        correct_predictions += 1

    print(f"  [{i+1:02d}] CoT={cot_len:3d} words | "
          f"CoT signal={cot_signal:.1f} | Pred={prediction} | "
          f"True={true_label} | {'✅' if is_correct else '❌'}")
    print(f"        CoT snippet: {cot_text[:120].strip()!r}")

    results_list.append({
        "Tweet"           : sample_tweet[:40] + "...",
        "True"            : true_label,
        "Pred"            : prediction,
        "✓?"              : "✅" if is_correct else "❌",
        "CoT Signal"      : round(cot_signal, 1),
        "CoT Tokens"      : cot_len,
        "Tokens Removed"  : 0,
        "γ"               : 0.00,
    })

accuracy_pct   = (correct_predictions / NUM_SAMPLES) * 100
avg_cot_tokens = total_cot_tokens / NUM_SAMPLES

print(f"\n{'='*60}")
print(f"🏆 BASELINE 1 ACCURACY          : {accuracy_pct:.1f}%  ({correct_predictions}/{NUM_SAMPLES})")
print(f"📏 Avg CoT Tokens (uncompressed) : {avg_cot_tokens:.1f} words")
print(f"✂️  Tokens Removed               : 0  (no compression)")
print(f"🔍 Verdict source               : extract_structured_cot_signal(full_cot)")
print(f"{'='*60}")

df1 = pd.DataFrame(results_list)
display(df1)

🚀 BASELINE 1 — Uncompressed CoT  (γ = 0.00)
   N = 100

  [01] CoT= 86 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY one of: Verdict: IRONIC\nVerdict: NON-IRONIC\nStep 1: Analyze the context and tone.\nThe tweet mentions a need for'
  [02] CoT= 72 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE REGARDING THE VERDICT:\n\nVerdict: IRONIC\nThe tweet uses irony by describing an action that seems ab'
  [03] CoT= 94 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "shirt. I don't even like the color. But I'm still going to wear it for the sake of the cause. \n\nStep 1: Analyze the con"
  [04] CoT= 52 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'The tweet seems to be expressing a direct statement rather than a sarcastic or humorous observation. The use of words'
  [05] CoT= 87 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: "To determine if this tweet is ironic or not, let's break it down step by step:\n\n1. Context: The tweet appears to be abo"
  [06] CoT= 87 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: "when you just said 'I hate corny jokes'. EXACTLY ONE VERDICT:\n\nVerdict: IRONIC\n\nStep 1: Analyze the context - The tweet"
  [07] CoT= 96 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY.\nStep 1: Analyze the content of the tweet.\nThe tweet mentions that people complain about the'
  [08] CoT= 92 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY\nStep 1: Analyze the content and context of the tweet.\nThe tweet mentions a "sock joke," which'
  [09] CoT= 94 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "To analyze this tweet, let's break it down step by step:\n\n1. Context: The tweet is about a situation involving someone"
  [10] CoT= 78 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY\nVerdict: IRONIC\nThe tweet criticizes people who dismiss anxiety by telling those with anxiety'
  [11] CoT= 92 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: '- "Always be prepared for anything" EXACTLY. \n\nStep 1: Analyze the content and context of the tweet.\nThe tweet is quoti'
  [12] CoT= 86 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "EXACTLY ONE RESPONSE\n\nTo determine if the tweet is ironic or non-ironic, let's analyze it step by step:\n\n1. Content of"
  [13] CoT= 88 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE VERDICT:\n\nVerdict: IRONIC\n\nStep 1: Analyze the content.\nThe tweet mentions loving "context and large ensemb'
  [14] CoT=  5 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE LINE Verdict: IRONIC'
  [15] CoT= 90 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY\nVerdict: IRONIC\nThe tweet appears to be ironic because it claims to have "never denied" the n'
  [16] CoT= 85 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY VERDICT:\n\nStep 1: Analyze the statement\'s content.\nThe tweet is about someone being "classy, never trashy, and'
  [17] CoT= 44 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'The tweet appears to be pointing out a common logical fallacy, where someone asserts something as a "fact" without prov'
  [18] CoT= 90 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY one of:\nVerdict: IRONIC\nVerdict: NON-IRONIC\n\nStep 1: Analyze the content of the tweet.\nThe tweet mentions sever'
  [19] CoT= 89 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY one of:\nVerdict: IRONIC\nVerdict: NON-IRONIC\n\nStep 1: Analyze the context.\nThe tweet seems to be responding to s'
  [20] CoT= 90 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'Step 1: Analyze the context and meaning of the tweet.\nThe tweet seems to be pointing out that someone (referred to as'
  [21] CoT= 76 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'To analyze the tweet for irony, let\'s break it down step by step:\n\n1. Content: The tweet says "Exam na jud. Merry Chris'
  [22] CoT= 68 words | CoT signal=0.0 | Pred=0 | True=1 | ❌
        CoT snippet: 'EXACTLY ONE RESPONSE PER QUESTION\nVerdict: NON-IRONIC\n\nThis tweet appears to be making a statement about irony rather t'
  [23] CoT= 85 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: "To determine if the tweet is ironic or non-ironic, let's break it down step by step:\n\n1. Content analysis:\n   - The twe"
  [24] CoT= 95 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY.\nVerdict: IRONIC\n\nThe tweet references the idea that hipsters are known for their ironic beha'
  [25] CoT= 90 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "Step 1: Analyze the content of the tweet.\nThe tweet consists of a simple question asking about the other person's wel"
  [26] CoT= 59 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'The tweet contains a hashtag (#sarcasm) that indicates sarcasm, which is a form of irony. In this case, the user is usi'
  [27] CoT= 53 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE LINE RESPONSE FOR VERDICT\nVerdict: IRONIC\nThe tweet suggests that looking like a "badass" (likely referring'
  [28] CoT= 54 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE\nVerdict: IRONIC\nThe tweet uses sarcasm to express disbelief that Charles Barkley, known for his po'
  [29] CoT= 89 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE VERDICT:\n\nVerdict: IRONIC\nStep 1: Analyze the content of the tweet.\nThe tweet suggests that staying up all'
  [30] CoT= 94 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'Step 1: Analyze the content of the tweet.\nThe tweet mentions a movie title "Bird of Prey" and the actor Natalie Prass.'
  [31] CoT= 86 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "To analyze this tweet, let's break it down step by step:\n\n1. Context: The user is expressing frustration about somethin"
  [32] CoT= 71 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY.\nVerdict: IRONIC\nThe tweet expresses a sentiment that being considered "hip" (a hipster) has'
  [33] CoT= 85 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "EXACTLY! I can't believe it's so close to midnight and I haven't even started my work yet... 'EXACTLY!' EXACTLY! EXACTL"
  [34] CoT= 83 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: '- I guess they meant to post "Top 50 Christian Songs for 2012" instead of \'Top 50 Teen Anal Casting\'. But it\'s still pr'
  [35] CoT= 83 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE VERDICT:\n\nVerdict: IRONIC\n\nStep 1: Analyze the content of the tweet.\nThe tweet mentions a hashtag related t'
  [36] CoT= 87 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY one of: Verdict: IRONIC\nVerdict: NON-IRONIC\n\nStep 1: Analyze the context and content of the tweet.\nThe tweet di'
  [37] CoT= 82 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE VERDICT:\n\nVerdict: IRONIC\n\nStep 1: Analyze the content - The tweet contains hashtags related to illegal und'
  [38] CoT=  6 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY\nVerdict: NON-IRONIC'
  [39] CoT= 92 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'To analyze this tweet, let\'s break it down step by step:\n\n1. The tweet mentions "got the truck buried today," which sou'
  [40] CoT= 93 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'To analyze this tweet, let\'s break it down step by step:\n\n1. Context: The tweet is about being on a train with "posh pe'
  [41] CoT= 90 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE PLEASE\nStep 1: Analyze the content of the tweet.\nThe tweet expresses frustration about having to v'
  [42] CoT= 80 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY one of: Verdict: IRONIC\nVerdict: NON-IRONIC\n\nStep 1: Analyze the content of the tweet.\nThe tweet mentions that'
  [43] CoT= 95 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: "EXACTLY ONE RESPONSE ONLY\n\nTo determine if this tweet is ironic or non-ironic, let's break it down step by step:\n\n1. Co"
  [44] CoT= 79 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY one of:\nVerdict: IRONIC\nVerdict: NON-IRONIC\nStep 1: Analyze the content of the tweet.\nThe tweet mentions that D'
  [45] CoT= 88 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE\n\nStep 1: Analyze the context and content of the tweet.\nThe tweet mentions a vacation and implies t'
  [46] CoT= 54 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'The tweet appears to be expressing disappointment or concern that someone might be missing out on something related to'
  [47] CoT= 90 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE\n\nStep 1: Analyze the context and meaning of the tweet.\nThe tweet mentions "having an afternoon sch'
  [48] CoT= 92 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY one of\nVerdict: IRONIC\nStep 1: Analyze the context and content of the tweet.\nThe tweet mentions a high number o'
  [49] CoT= 98 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "EXACTLY ONE RESPONSE ONLY.\n\nTo determine if the tweet is ironic or non-ironic, let's analyze its content step by step:"
  [50] CoT= 86 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'The tweet appears to be a statement about music being created for the benefit of the general public rather than as a me'
  [51] CoT= 85 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: "EXACTLY ONE RESPONSE\nVerdict: IRONIC\n\nThe tweet is using irony by juxtaposing the normal reason for a game's postponeme"
  [52] CoT= 97 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY.\nStep 1: Analyze the content of the tweet.\nThe tweet is instructing people on how to find a l'
  [53] CoT= 90 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "when I see all these people celebrating Christmas and other western holidays in Africa. It's sad to see how much we've"
  [54] CoT= 88 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE\n\nStep 1: Analyze the context and content of the tweet.\nThe tweet mentions being at the Emergency R'
  [55] CoT= 85 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY\nStep 1: Analyze the context of the tweet.\nThe tweet mentions someone (Suhs) being clean for 2'
  [56] CoT= 86 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "EXACTLY ONE VERDICT\nTo determine if the tweet is ironic or non-ironic, let's break it down step by step:\n\n1. Context: T"
  [57] CoT= 87 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE\nVerdict: NON-IRONIC\nThe tweet is describing a situation where Haley is happy about her new hammock'
  [58] CoT= 88 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE!\nVerdict: IRONIC\nThe tweet contains a double irony. First, it expresses frustration at the ongoing'
  [59] CoT= 76 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE RESPONSE FOR THE WHOLE SCENARIO Please.\nVerdict: IRONIC\nThe tweet appears to be ironic because it contrasts'
  [60] CoT= 47 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'The tweet does not contain any sarcasm or hyperbole that would indicate irony. It simply announces the availability of'
  [61] CoT= 45 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: "The tweet criticizes Trestman's performance in the NFL and suggests that he has no future in the league. However, it do"
  [62] CoT= 87 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE\nVerdict: IRONIC\nThe tweet suggests irony through the context and punctuation. The person expresses'
  [63] CoT=  6 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY\n\nVerdict: IRONIC'
  [64] CoT= 94 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: "EXACTLY ONE RESPONSE\n\nStep 1: Analyze the context and tone of the tweet.\nThe tweet describes a worker's concern about t"
  [65] CoT= 92 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE\nStep 1: Analyze the content of the tweet.\nThe tweet says "I just love being ignored😊|#not😒" and us'
  [66] CoT= 95 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE VERDICT:\n\nStep 1: Analyze the content of the tweet.\nThe tweet criticizes someone who gave a bad review due'
  [67] CoT= 74 words | CoT signal=0.0 | Pred=0 | True=1 | ❌
        CoT snippet: 'The tweet "Produce Mobile Apps #not" does not contain any clear indication of irony. It\'s a straightforward statement e'
  [68] CoT= 89 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: "To determine if this tweet is ironic or non-ironic, let's break it down step by step:\n\n1. Content analysis:\n   - The tw"
  [69] CoT= 85 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY one of: Verdict: IRONIC\nVerdict: NON-IRONIC\n\nStep 1: Analyze the content of the tweet.\nThe tweet mentions that'
  [70] CoT= 98 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "To analyze the tweet for irony, let's break it down step by step:\n\n1. Content of the tweet: It's a standard holiday gre"
  [71] CoT= 37 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: "The tweet is comparing two unrelated events to a third event that has recently happened. There's no clear sarcasm or co"
  [72] CoT= 86 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "EXACTLY ONE RESPONSE ONLY\n\nTo determine if the tweet is ironic or non-ironic, let's analyze it step by step:\n\n1. Contex"
  [73] CoT= 96 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY.\nStep 1: Analyze the content of the tweet.\nThe tweet describes a scenario where the author pr'
  [74] CoT= 45 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'EXACTLY ONE SENTENCE ANSWER: The tweet seems to be expressing a surprise at having the entire weekend off, but it doesn'
  [75] CoT= 35 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'EXACTLY ONE LINE RESPONSE:\n\nThe tweet is asking about the number of jobs that pay middle-class wages among a large numb'
  [76] CoT= 91 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY! Step 1: Analyze the content of the tweet.\nThe tweet discusses a perceived difference in pref'
  [77] CoT= 91 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'Step 1: Analyze the content of the tweet.\nThe tweet mentions a campaign called "#bornrisky" and highlights various asp'
  [78] CoT= 81 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "EXACTLY ONE RESPONSE ONLY.\nTo determine if the tweet is ironic or not, let's break it down step by step:\n\n1. Content An"
  [79] CoT= 67 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY one of:\nVerdict: IRONIC\nVerdict: NON-IRONIC\nStep 1: Analyze the tweet for any clear indication of irony. The tw'
  [80] CoT= 97 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'Step 1: Analyze the content of the tweet.\nThe tweet is praising the quality and origin (British-made) of a product.\n\nS'
  [81] CoT= 97 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE RESPONSE\nStep 1: Analyze the content of the tweet.\nThe tweet states that the sender sent something but it w'
  [82] CoT= 77 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "EXACTLY ONE RESPONSE ONLY.\nTo determine if the tweet is ironic or not, let's break it down step by step:\n\n1. The tweet"
  [83] CoT= 89 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'Step 1: Analyze the context and content of the tweet.\nThe tweet contains a series of hashtags and mentions, including'
  [84] CoT= 69 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY! Verdict: IRONIC\n\nThe tweet uses the hashtag "#irony" to indicate that the statement "Niagara'
  [85] CoT= 93 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE\nVerdict: IRONIC\nThe tweet suggests a humorous or sarcastic tone by using the context of a sports v'
  [86] CoT=101 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'Step 1: Analyze the context and meaning of the tweet.\nThe tweet contains information about a situation involving murde'
  [87] CoT= 85 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY one of: Verdict: IRONIC\nVerdict: NON-IRONIC\n\nStep-by-step analysis:\n1. The tweet discusses a tribunal that has'
  [88] CoT= 86 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: "EXACTLY ONE RESPONSE ONLY! Verdict: IRONIC\n\nThe tweet suggests a contradiction between the protesters' actions (chantin"
  [89] CoT= 86 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: "I think you're missing something here. The expansion was a response to Russia's actions and the Cold War. It wasn't jus"
  [90] CoT= 93 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: "Step 1: Analyze the use of irony indicators.\nThe tweet uses hashtags like '#Irony' and mentions 'no money', which sug"
  [91] CoT= 93 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: "The tweet appears to be cut off at the end and doesn't provide a clear context for the statement about responsibilities"
  [92] CoT= 72 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE ONLY!\nVerdict: IRONIC\n\nThe tweet uses the phrase "trickle down fairy" which is a sarcastic and iro'
  [93] CoT= 81 words | CoT signal=0.0 | Pred=0 | True=0 | ✅
        CoT snippet: 'EXACTLY ONE RESPONSE FOR EACH TWEET\nVerdict: NON-IRONIC\n\nThe tweet appears to be a statement of frustration directed at'
  [94] CoT= 83 words | CoT signal=0.5 | Pred=1 | True=1 | ✅
        CoT snippet: "EXACTLY ONE RESPONSE ENDING WITH AN ANSWER DIGIT. To determine if this tweet is ironic or non-ironic, let's analyze it"
  [95] CoT= 77 words | CoT signal=1.0 | Pred=1 | True=1 | ✅
        CoT snippet: 'EXACTLY one of: Verdict: IRONIC\nVerdict: NON-IRONIC\n\nStep 1: Analyze the context of the tweet.\nThe tweet mentions the "'
  [96] CoT= 81 words | CoT signal=1.0 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE VERDICT:\n\nVerdict: IRONIC\n\nStep 1: Analyze the content of the tweet.\nThe tweet mentions "the last day of th'
  [97] CoT= 96 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'EXACTLY ONE RESPONSE FOR REVIEW\nStep 1: Analyze the content of the tweet.\nThe tweet mentions a child (10) asking if Chr'
  [98] CoT= 94 words | CoT signal=0.5 | Pred=1 | True=0 | ❌
        CoT snippet: 'Step 1: Analyze the context and content of the tweet.\nThe tweet appears to be a simple, friendly message wishing some'
  [99] CoT= 92 words | CoT signal=1.0 | Pred=1 | True=0 | ❌

,Tweet,True,Pred,✓?,CoT Signal,CoT Tokens,Tokens Removed,γ
0,@user Can U Help?||More conservatives ne...,0,1,❌,1.0,86,0,0.0
1,Just walked in to #Starbucks and asked f...,1,1,✅,1.0,72,0,0.0
2,#NOT GONNA WIN...,0,1,❌,0.5,94,0,0.0
3,@user He is exactly that sort of person....,0,0,✅,0.0,52,0,0.0
4,So much #sarcasm at work mate 10/10 #bor...,1,1,✅,0.5,87,0,0.0
...,...,...,...,...,...,...,...,...
95,The last day of the year and I will be t...,0,1,❌,1.0,81,0,0.0
96,MB forgot to move the elf on shelf and n...,0,1,❌,0.5,96,0,0.0
97,"@user happy new year, da! Thanks sobra f...",0,1,❌,0.5,94,0,0.0
98,WATCH: #Megatron from #Transformers Rant...,0,1,❌,1.0,92,0,0.0
99,@user @user #not #working when are we ab...,0,1,❌,0.5,95,0,0.0

Vanilla TokenSkip

In [7]:
import pandas as pd
from IPython.display import display

# ════════════════════════════════════════════════════════════════════════════
# BASELINE 2 — Vanilla TokenSkip  (γ = 0.50, static)
#
# What this measures:
#   • Accuracy  : Verdict extracted from the COMPRESSED CoT via
#                 extract_structured_cot_signal. Because vanilla_compress()
#                 prunes purely on stopword status and token length — with no
#                 task-aware gradient protection — it blindly shreds the
#                 "Verdict:" line and critical contrastive connectors (not,
#                 but, never). The parser therefore falls back to 0.5
#                 (ambiguous) or reads a corrupted conclusion, organically
#                 tanking accuracy below the uncompressed baseline.
#   • Avg tokens: compressed CoT word count (target ≈ 50% of original).
#
# No entropy, no gradients, no critical-token protection.
# This is the exact robustness failure that RDS is designed to fix.
# ════════════════════════════════════════════════════════════════════════════

VANILLA_GAMMA = 0.50
NUM_SAMPLES   = 100

results_list        = []
correct_predictions = 0
total_orig_tokens   = 0
total_comp_tokens   = 0
verdict_found_count = 0

print(f"🚀 BASELINE 2 — Vanilla TokenSkip  (γ = {VANILLA_GAMMA}, static)")
print(f"   N = {NUM_SAMPLES}\n")

for i in range(NUM_SAMPLES):
    sample_tweet = test_data[i]["text"]
    true_label   = test_data[i]["label"]

    # ── Generate CoT ──────────────────────────────────────────────────────
    prompt = STRUCTURED_PROMPT.format(tweet=sample_tweet)
    inputs = qwen_tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = qwen_model.generate(
            **inputs,
            max_new_tokens=120
        )

    generated_ids = outputs[0][inputs["input_ids"].shape[1]:]
    cot_text      = qwen_tokenizer.decode(generated_ids, skip_special_tokens=True)
    orig_len      = len(cot_text.split())
    total_orig_tokens += orig_len

    # ── Static 50% compression — no critical-token protection ─────────────
    # vanilla_compress() drops stopwords and short words first, making it
    # highly likely to remove "Verdict:", "not", "but", "never", etc.
    compressed_text = vanilla_compress(cot_text, gamma=VANILLA_GAMMA)
    comp_len        = len(compressed_text.split())
    total_comp_tokens += comp_len
    tokens_removed  = orig_len - comp_len

    # ── Extract verdict from the COMPRESSED CoT ───────────────────────────
    # This is the critical difference from the buggy original: we now judge
    # the compressed reasoning — not the raw tweet — mirroring how RDS works.
    # Blind pruning will often destroy the verdict line → cot_signal = 0.5
    # (ambiguous fallback), which defaults prediction to 0 and causes errors.
    cot_signal = extract_structured_cot_signal(compressed_text)
    prediction = int(cot_signal >= 0.5)   # 0.5 (ambiguous) → non-ironic (0)

    verdict_survived = (cot_signal != 0.5)
    if verdict_survived:
        verdict_found_count += 1

    is_correct = (prediction == true_label)
    if is_correct:
        correct_predictions += 1

    print(f"  [{i+1:02d}] Orig={orig_len:3d} → Comp={comp_len:3d} words "
          f"(removed {tokens_removed:2d}) | "
          f"CoT signal={cot_signal:.1f} {'✔verdict' if verdict_survived else '⚠️ verdict LOST'} | "
          f"Pred={prediction} | True={true_label} | {'✅' if is_correct else '❌'}")

    results_list.append({
        "Tweet"           : sample_tweet[:40] + "...",
        "True"            : true_label,
        "Pred"            : prediction,
        "✓?"              : "✅" if is_correct else "❌",
        "CoT Signal"      : round(cot_signal, 1),
        "Verdict Survived": "✔" if verdict_survived else "✘ LOST",
        "Orig Tokens"     : orig_len,
        "Comp Tokens"     : comp_len,
        "Tokens Removed"  : tokens_removed,
        "γ"               : VANILLA_GAMMA,
    })

accuracy_pct    = (correct_predictions / NUM_SAMPLES) * 100
avg_orig_tokens = total_orig_tokens / NUM_SAMPLES
avg_comp_tokens = total_comp_tokens / NUM_SAMPLES
verdict_survival_rate = (verdict_found_count / NUM_SAMPLES) * 100

print(f"\n{'='*60}")
print(f"🏆 BASELINE 2 ACCURACY                : {accuracy_pct:.1f}%  ({correct_predictions}/{NUM_SAMPLES})")
print(f"📏 Avg CoT Tokens — Original           : {avg_orig_tokens:.1f} words")
print(f"📏 Avg CoT Tokens — After Vanilla Skip : {avg_comp_tokens:.1f} words")
print(f"✂️  Avg Tokens Removed (static 50%)     : {avg_orig_tokens - avg_comp_tokens:.1f} words")
print(f"🔍 Verdict survived compression        : {verdict_found_count}/{NUM_SAMPLES} ({verdict_survival_rate:.0f}%)")
print(f"🔍 Verdict source                      : extract_structured_cot_signal(compressed_cot)")
print(f"{'='*60}")
print()
print("⚠️  NOTE: Low verdict survival rate above directly explains depressed accuracy.")
print("   Vanilla pruning destroys the 'Verdict:' line and contrastive connectors")
print("   ('not', 'but', 'never'), causing the parser to default to 0.5 (ambiguous)")
print("   and forcing prediction = 0 (non-ironic) for ambiguous cases.")

df2 = pd.DataFrame(results_list)
display(df2)

🚀 BASELINE 2 — Vanilla TokenSkip  (γ = 0.5, static)
   N = 100

  [01] Orig= 87 → Comp= 43 words (removed 44) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [02] Orig= 81 → Comp= 40 words (removed 41) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [03] Orig= 77 → Comp= 38 words (removed 39) | CoT signal=0.0 ✔verdict | Pred=0 | True=0 | ✅
  [04] Orig= 86 → Comp= 43 words (removed 43) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [05] Orig= 67 → Comp= 33 words (removed 34) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [06] Orig= 41 → Comp= 20 words (removed 21) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [07] Orig= 78 → Comp= 39 words (removed 39) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [08] Orig= 70 → Comp= 35 words (removed 35) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [09] Orig= 97 → Comp= 48 words (removed 49) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [10] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [11] Orig= 88 → Comp= 44 words (removed 44) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [12] Orig= 37 → Comp= 18 words (removed 19) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [13] Orig= 82 → Comp= 41 words (removed 41) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [14] Orig=  5 → Comp=  5 words (removed  0) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [15] Orig= 86 → Comp= 43 words (removed 43) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [16] Orig= 86 → Comp= 43 words (removed 43) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [17] Orig= 42 → Comp= 21 words (removed 21) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [18] Orig= 83 → Comp= 41 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [19] Orig= 89 → Comp= 44 words (removed 45) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [20] Orig= 89 → Comp= 44 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [21] Orig= 82 → Comp= 41 words (removed 41) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [22] Orig= 99 → Comp= 49 words (removed 50) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [23] Orig= 91 → Comp= 45 words (removed 46) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [24] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [25] Orig= 89 → Comp= 44 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [26] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [27] Orig= 56 → Comp= 28 words (removed 28) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [28] Orig= 83 → Comp= 41 words (removed 42) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [29] Orig= 83 → Comp= 41 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [30] Orig=  5 → Comp=  5 words (removed  0) | CoT signal=0.0 ✔verdict | Pred=0 | True=0 | ✅
  [31] Orig= 39 → Comp= 19 words (removed 20) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [32] Orig=  6 → Comp=  5 words (removed  1) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [33] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [34] Orig= 85 → Comp= 42 words (removed 43) | CoT signal=0.0 ✔verdict | Pred=0 | True=0 | ✅
  [35] Orig= 87 → Comp= 43 words (removed 44) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [36] Orig= 92 → Comp= 46 words (removed 46) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [37] Orig= 77 → Comp= 38 words (removed 39) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [38] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=0.0 ✔verdict | Pred=0 | True=0 | ✅
  [39] Orig= 91 → Comp= 45 words (removed 46) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [40] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [41] Orig= 87 → Comp= 43 words (removed 44) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [42] Orig= 83 → Comp= 41 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [43] Orig=  6 → Comp=  5 words (removed  1) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [44] Orig= 83 → Comp= 41 words (removed 42) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [45] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [46] Orig= 94 → Comp= 47 words (removed 47) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [47] Orig=  5 → Comp=  5 words (removed  0) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [48] Orig= 85 → Comp= 42 words (removed 43) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [49] Orig= 67 → Comp= 33 words (removed 34) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [50] Orig= 92 → Comp= 46 words (removed 46) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [51] Orig=  6 → Comp=  5 words (removed  1) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [52] Orig= 40 → Comp= 20 words (removed 20) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [53] Orig=  7 → Comp=  5 words (removed  2) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [54] Orig= 77 → Comp= 38 words (removed 39) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [55] Orig= 87 → Comp= 43 words (removed 44) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [56] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [57] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [58] Orig= 10 → Comp=  5 words (removed  5) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [59] Orig= 80 → Comp= 40 words (removed 40) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [60] Orig= 92 → Comp= 46 words (removed 46) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [61] Orig= 94 → Comp= 47 words (removed 47) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [62] Orig= 85 → Comp= 42 words (removed 43) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [63] Orig= 93 → Comp= 46 words (removed 47) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [64] Orig= 10 → Comp=  5 words (removed  5) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [65] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [66] Orig= 94 → Comp= 47 words (removed 47) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [67] Orig= 91 → Comp= 45 words (removed 46) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [68] Orig= 89 → Comp= 44 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [69] Orig= 79 → Comp= 39 words (removed 40) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [70] Orig= 94 → Comp= 47 words (removed 47) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [71] Orig=104 → Comp= 52 words (removed 52) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [72] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [73] Orig=  7 → Comp=  5 words (removed  2) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [74] Orig= 95 → Comp= 47 words (removed 48) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [75] Orig= 33 → Comp= 16 words (removed 17) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [76] Orig= 96 → Comp= 48 words (removed 48) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [77] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [78] Orig= 93 → Comp= 46 words (removed 47) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [79] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [80] Orig= 97 → Comp= 48 words (removed 49) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [81] Orig= 67 → Comp= 33 words (removed 34) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [82] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [83] Orig= 56 → Comp= 28 words (removed 28) | CoT signal=0.0 ✔verdict | Pred=0 | True=0 | ✅
  [84] Orig= 79 → Comp= 39 words (removed 40) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [85] Orig= 78 → Comp= 39 words (removed 39) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [86] Orig= 45 → Comp= 22 words (removed 23) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [87] Orig= 88 → Comp= 44 words (removed 44) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [88] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [89] Orig= 37 → Comp= 18 words (removed 19) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [90] Orig= 88 → Comp= 44 words (removed 44) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [91] Orig= 38 → Comp= 19 words (removed 19) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [92] Orig= 90 → Comp= 45 words (removed 45) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [93] Orig= 63 → Comp= 31 words (removed 32) | CoT signal=0.0 ✔verdict | Pred=0 | True=0 | ✅
  [94] Orig= 92 → Comp= 46 words (removed 46) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=1 | ✅
  [95] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=1 | ✅
  [96] Orig= 89 → Comp= 44 words (removed 45) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [97] Orig= 84 → Comp= 42 words (removed 42) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌
  [98] Orig= 59 → Comp= 29 words (removed 30) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [99] Orig= 95 → Comp= 47 words (removed 48) | CoT signal=0.5 ⚠️ verdict LOST | Pred=1 | True=0 | ❌
  [100] Orig= 81 → Comp= 40 words (removed 41) | CoT signal=1.0 ✔verdict | Pred=1 | True=0 | ❌

============================================================
🏆 BASELINE 2 ACCURACY                : 48.0%  (48/100)
📏 Avg CoT Tokens — Original           : 73.1 words
📏 Avg CoT Tokens — After Vanilla Skip : 36.5 words
✂️  Avg Tokens Removed (static 50%)     : 36.6 words
🔍 Verdict survived compression        : 40/100 (40%)
🔍 Verdict source                      : extract_structured_cot_signal(compressed_cot)
============================================================

⚠️  NOTE: Low verdict survival rate above directly explains depressed accuracy.
   Vanilla pruning destroys the 'Verdict:' line and contrastive connectors
   ('not', 'but', 'never'), causing the parser to default to 0.5 (ambiguous)
   and forcing prediction = 0 (non-ironic) for ambiguous cases.

,Tweet,True,Pred,✓?,CoT Signal,Verdict Survived,Orig Tokens,Comp Tokens,Tokens Removed,γ
0,@user Can U Help?||More conservatives ne...,0,1,❌,1.0,✔,87,43,44,0.5
1,Just walked in to #Starbucks and asked f...,1,1,✅,1.0,✔,81,40,41,0.5
2,#NOT GONNA WIN...,0,0,✅,0.0,✔,77,38,39,0.5
3,@user He is exactly that sort of person....,0,1,❌,0.5,✘ LOST,86,43,43,0.5
4,So much #sarcasm at work mate 10/10 #bor...,1,1,✅,1.0,✔,67,33,34,0.5
...,...,...,...,...,...,...,...,...,...,...
95,The last day of the year and I will be t...,0,1,❌,1.0,✔,89,44,45,0.5
96,MB forgot to move the elf on shelf and n...,0,1,❌,1.0,✔,84,42,42,0.5
97,"@user happy new year, da! Thanks sobra f...",0,1,❌,0.5,✘ LOST,59,29,30,0.5
98,WATCH: #Megatron from #Transformers Rant...,0,1,❌,0.5,✘ LOST,95,47,48,0.5
99,@user @user #not #working when are we ab...,0,1,❌,1.0,✔,81,40,41,0.5