First, we need to set up the environment with the necessary Hugging Face libraries, including bitsandbytes for memory-efficient model loading and llmlingua for the base token importance.

In [1]:
!pip install -q transformers datasets accelerate bitsandbytes torch
!pip install -q llmlingua

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.5 MB/s eta 0:00:00

We will load the TweetEval dataset, the RoBERTa classifier, and the Qwen2.5 generator.

In [2]:
import torch
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoModelForSequenceClassification, BitsAndBytesConfig
from datasets import load_dataset

device = "cuda" if torch.cuda.is_available() else "cpu"

# 1. Load Dataset (TweetEval - Irony)
print("Loading Dataset...")
dataset = load_dataset("tweet_eval", "irony")
test_data = dataset['test']

# 2. Load Evaluation Classifier (RoBERTa)
print("Loading RoBERTa Classifier...")
roberta_name = "cardiffnlp/twitter-roberta-base-irony"
rob_tokenizer = AutoTokenizer.from_pretrained(roberta_name)
rob_model = AutoModelForSequenceClassification.from_pretrained(roberta_name).to(device)

# 3. Define the 4-bit Quantization Configuration
print("Configuring 4-bit Quantization...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16 # Speeds up computation on T4
)

# 4. Load Reasoning Generator (Qwen 3B with updated quantization)
print("Loading Qwen2.5-3B...")
qwen_name = "Qwen/Qwen2.5-3B-Instruct"
qwen_tokenizer = AutoTokenizer.from_pretrained(qwen_name)
qwen_model = AutoModelForCausalLM.from_pretrained(
    qwen_name,
    device_map="auto",
    quantization_config=bnb_config
)

Loading Dataset...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

irony/train-00000-of-00001.parquet:   0%|          | 0.00/183k [00:00<?, ?B/s]

irony/test-00000-of-00001.parquet:   0%|          | 0.00/54.0k [00:00<?, ?B/s]

irony/validation-00000-of-00001.parquet:   0%|          | 0.00/61.1k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2862 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/784 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/955 [00:00<?, ? examples/s]

Loading RoBERTa Classifier...

config.json:   0%|          | 0.00/705 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-irony
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Configuring 4-bit Quantization...
Loading Qwen2.5-3B...

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

This cell translates our equation for $H(c)$ and the scaled sigmoid transformation into code. It extracts the logits from Qwen's generation to calculate how "uncertain" or complex the reasoning is.

In [3]:
import torch
import torch.nn.functional as F
import math

def calculate_dynamic_gamma(logits, min_gamma=0.1, max_gamma=0.9, k=1.0, mu=0.5):
    """
    Calculates the reasoning entropy and maps it to a dynamic compression ratio.
    """
    # Convert logits to probabilities
    probs = F.softmax(logits, dim=-1)

    # Epsilon (1e-9) to prevent log(0) yielding -inf and breaking the sum into a nan
    epsilon = 1e-9
    entropy_tensor = -torch.sum(probs * torch.log(probs + epsilon), dim=-1)
    entropy = entropy_tensor.mean().item()

    # Fallback catch just in case a nan slips through due to precision limits
    if math.isnan(entropy):
        entropy = 0.0

    # USING math.exp instead of np.exp since entropy is a standard float here
    gamma_dyn = min_gamma + (max_gamma - min_gamma) / (1 + math.exp(-k * (entropy - mu)))

    return gamma_dyn, entropy

This is the core of the adversarial robustness. We pass the text through RoBERTa, grab the embeddings, and compute the gradient of the loss with respect to those embeddings.

In [4]:
def get_gradient_sensitivity(text, rob_tokenizer, rob_model, device, target_class=1):
    """
    Approximates token impact by checking the gradient norm of the embeddings
    during a backward pass in the RoBERTa classifier.
    """
    inputs = rob_tokenizer(text, return_tensors="pt").to(device)

    # Get the embedding layer output and retain its gradients
    embeddings = rob_model.roberta.embeddings.word_embeddings(inputs['input_ids'])
    embeddings.retain_grad()

    # Forward pass
    outputs = rob_model(inputs_embeds=embeddings, attention_mask=inputs['attention_mask'])
    logits = outputs.logits

    # Compute a dummy loss against the predicted or target class
    loss = F.cross_entropy(logits, torch.tensor([target_class]).to(device))

    # Backward pass to get gradients
    rob_model.zero_grad()
    loss.backward()

    # Calculate the L2 norm of the gradients for each token
    grad_norms = embeddings.grad.norm(dim=-1).squeeze().cpu().numpy()

    # Map back to tokens
    tokens = rob_tokenizer.convert_ids_to_tokens(inputs['input_ids'].squeeze())

    # Explicit list of tokens and punctuation to completely ignore
    skip_tokens = {'<s>', '</s>', '<pad>', '<unk>', '.', ',', ':', '"', "'", '?', '!'}

    sensitivity_scores = {}
    for token, grad in zip(tokens, grad_norms):
        # Clean special characters from RoBERTa tokens (like Ġ)
        clean_token = token.replace('Ġ', '').strip()

        # Filtering logic to ignore special tokens and single-character noise
        if clean_token and token not in skip_tokens and len(clean_token) > 1:
            # If a word is split into subwords, keep the max gradient value
            if clean_token in sensitivity_scores:
                sensitivity_scores[clean_token] = max(sensitivity_scores[clean_token], float(grad))
            else:
                sensitivity_scores[clean_token] = float(grad)

    return sensitivity_scores

Ablation

In [5]:
import torch
import torch.nn.functional as F
import nltk, re
from nltk.corpus import stopwords

nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)

def classify_tweet(tweet_text, rob_tokenizer, rob_model, device):
    """Classify the raw tweet and return (predicted_class, logits_tensor)."""
    inputs = rob_tokenizer(tweet_text, return_tensors="pt",
                           truncation=True, max_length=128).to(device)
    with torch.no_grad():
        outputs = rob_model(**inputs)
    logits = outputs.logits
    prediction = torch.argmax(logits, dim=-1).item()
    return prediction, logits


# ─────────────────────────────────────────────────────────────────────────────
# ROOT CAUSE FIX: The old keyword scanner gave cot_signal=1.0 for almost every
# tweet because Qwen uses words like "ironic" and "sarcasm" even when describing
# WHY something is NOT ironic. This made the CoT signal useless.
#
# NEW APPROACH: Parse only the VERDICT LINE that Qwen is prompted to output at
# the end of its reasoning ("Verdict: IRONIC" / "Verdict: NON-IRONIC").
# This is a hard 0/1 signal from Qwen's actual conclusion, not its vocabulary.
#
# Fallback: if the verdict line is missing, scan only the FINAL 2 SENTENCES
# (the conclusion), not the full CoT body where analytical vocabulary pollutes.
# ─────────────────────────────────────────────────────────────────────────────
def extract_structured_cot_signal(cot_text):
    """
    Returns a float in {0.0, 0.5, 1.0}:
      1.0 → Qwen explicitly concluded IRONIC
      0.0 → Qwen explicitly concluded NON-IRONIC
      0.5 → No clear verdict found (neutral / abstain)
    """
    lower = cot_text.lower()

    # Priority 1: explicit verdict line
    verdict_match = re.search(
        r"verdict\s*[:\-]\s*(ironic|non[- ]?ironic|not ironic|sarcastic|not sarcastic)",
        lower
    )
    if verdict_match:
        v = verdict_match.group(1)
        if "non" in v or "not" in v:
            return 0.0
        else:
            return 1.0

    # Priority 2: scan only the final 2 sentences
    sentences = re.split(r"(?<=[.!?])\s+", cot_text.strip())
    conclusion = " ".join(sentences[-2:]).lower() if len(sentences) >= 2 else lower

    CONCLUDE_IRONIC   = {"is ironic", "is sarcastic", "contains irony",
                         "irony is present", "this is ironic", "therefore ironic",
                         "tweet is ironic", "concludes ironic"}
    CONCLUDE_NONIRONIC = {"is not ironic", "is not sarcastic", "no irony",
                          "not ironic", "non-ironic", "sincere", "literal statement",
                          "therefore not", "no sarcasm", "not sarcastic"}

    ironic_hits    = sum(1 for p in CONCLUDE_IRONIC    if p in conclusion)
    nonironic_hits = sum(1 for p in CONCLUDE_NONIRONIC if p in conclusion)

    if ironic_hits > nonironic_hits:    return 1.0
    if nonironic_hits > ironic_hits:    return 0.0
    return 0.5   # genuinely ambiguous conclusion


# ─────────────────────────────────────────────────────────────────────────────
# entropy_to_alpha  — the entropy-gated adaptive fusion weight
# KEY INSIGHT (from ablation analysis):
#   ENTROPY_ONLY outperforms FULL_RDS because the CoT signal was too noisy.
#   But entropy itself IS informative:
#     Low H(c)  → Qwen generated confidently → its verdict is more trustworthy
#                 → reduce alpha (give CoT more weight)
#     High H(c) → Qwen was uncertain during generation → verdict less reliable
#                 → raise alpha (lean on RoBERTa more)
# This replaces the fixed alpha=0.7 with a function of entropy.
# ─────────────────────────────────────────────────────────────────────────────
def entropy_to_alpha(entropy,
                     low_thresh=0.2, high_thresh=0.5,
                     alpha_low=0.55,  alpha_high=0.85):
    """
    Maps reasoning entropy to a RoBERTa weight (alpha).
      entropy <= low_thresh  → alpha = alpha_low  (trust CoT more)
      entropy >= high_thresh → alpha = alpha_high (trust RoBERTa more)
      in between             → linear interpolation
    """
    if entropy <= low_thresh:
        return alpha_low
    elif entropy >= high_thresh:
        return alpha_high
    else:
        t = (entropy - low_thresh) / (high_thresh - low_thresh)
        return alpha_low + t * (alpha_high - alpha_low)


# ─────────────────────────────────────────────────────────────────────────────
# fused_classify_v2  — the improved decision function

# Formula:
#   alpha = entropy_to_alpha(H(c))       ← dynamic, not fixed
#   p_final = alpha * p_RoBERTa + (1-alpha) * p_CoT_verdict
# ─────────────────────────────────────────────────────────────────────────────
def fused_classify_v2(tweet_text, cot_text, entropy,
                      rob_tokenizer, rob_model, device):
    """
    Entropy-gated fusion of RoBERTa tweet probability and Qwen verdict signal.
    Returns: (prediction, roberta_prob, cot_signal, alpha, fused_prob)
    """
    # RoBERTa on the original tweet
    _, tweet_logits = classify_tweet(tweet_text, rob_tokenizer, rob_model, device)
    tweet_probs = F.softmax(tweet_logits, dim=-1).squeeze().cpu()
    p_roberta = tweet_probs[1].item()   # P(ironic) from RoBERTa

    # Qwen structured verdict
    cot_signal = extract_structured_cot_signal(cot_text)

    # Entropy-adaptive alpha
    alpha = entropy_to_alpha(entropy)

    # Weighted fusion
    p_fused = alpha * p_roberta + (1 - alpha) * cot_signal
    prediction = int(p_fused >= 0.5)

    return prediction, p_roberta, cot_signal, alpha, p_fused


# ─────────────────────────────────────────────────────────────────────────────
# improved compress_cot  (contrastive connectors preserved)
# ─────────────────────────────────────────────────────────────────────────────
CONTRASTIVE_CONNECTORS = {
    "but", "yet", "though", "although", "however", "despite", "while",
    "whereas", "still", "even", "never", "not", "no", "without", "barely"
}

def compress_cot_improved(original_text, gamma_dyn, critical_tokens):
    stop_words = set(stopwords.words("english")) - CONTRASTIVE_CONNECTORS
    words = original_text.split()
    target_length = max(5, int(len(words) * (1.0 - gamma_dyn)))
    scored_words = []
    for idx, word in enumerate(words):
        clean = word.lower().strip(".,!?\"'")
        is_critical = any(crit.lower() in clean for crit in critical_tokens if len(crit) >= 4)
        if is_critical:                              score = 1000
        elif clean in CONTRASTIVE_CONNECTORS:        score = 500
        elif clean not in stop_words and len(clean) >= 3: score = 10
        else:                                        score = 1
        scored_words.append((idx, word, score))
    scored_words.sort(key=lambda x: x[2], reverse=True)
    kept = sorted(scored_words[:target_length], key=lambda x: x[0])
    return " ".join(w[1] for w in kept)

print("✅ All upgraded helper functions loaded.")
print("   • extract_structured_cot_signal  — verdict-line parser (fixes noisy CoT signal)")
print("   • entropy_to_alpha               — entropy-gated adaptive fusion weight")
print("   • fused_classify_v2              — improved decision function")

✅ All upgraded helper functions loaded.
   • extract_structured_cot_signal  — verdict-line parser (fixes noisy CoT signal)
   • entropy_to_alpha               — entropy-gated adaptive fusion weight
   • fused_classify_v2              — improved decision function

This cell loops through a few test examples. It prompts Qwen for a Chain-of-Thought, calculates the dynamic budget, extracts the gradient sensitivities, and prepares the data for the final fusion.

In [10]:
import torch
import pandas as pd
from IPython.display import display

# ────────────────────────────────────────────────────────────────
# IMPROVED MAIN PIPELINE  —  RDS v2
#
# Three targeted upgrades over the previous version:
#
#   [1] Structured CoT verdict prompt
#       Qwen is now asked to end its reasoning with an explicit "Verdict: IRONIC"
#       or "Verdict: NON-IRONIC" line. This replaces the noisy keyword scan that
#       was returning signal=1.0 for almost every tweet.
#
#   [2] Entropy-gated adaptive alpha
#       Alpha is no longer fixed at 0.7. Low entropy (confident Qwen) → lower
#       alpha (trust Qwen more). High entropy (uncertain Qwen) → higher alpha
#       (trust RoBERTa more). Derived from the ablation study showing
#       ENTROPY_ONLY beat FULL_RDS because the CoT signal was corrupted.
#
#   [3] Fusion on p_ironic directly
#       No change to the fusion arithmetic — just cleaner inputs.
# ────────────────────────────────────────────────────────────────

STRUCTURED_PROMPT = (
    "Analyze whether the following tweet is ironic or non-ironic. "
    "Think step-by-step, then end your response with EXACTLY one of:\n"
    "Verdict: IRONIC\n"
    "Verdict: NON-IRONIC\n\n"
    "Tweet: \'{tweet}\'"
)

def generate_cot_and_analyze_v2(tweet, mode="FULL_RDS", tweet_num=""):
    num_str = f" {tweet_num}" if tweet_num else ""
    print(f"\n--- Processing Tweet{num_str}: {tweet[:60]}... ---")

    prompt = STRUCTURED_PROMPT.format(tweet=tweet)
    inputs = qwen_tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = qwen_model.generate(
            **inputs,
            max_new_tokens=120,
            return_dict_in_generate=True,
            output_scores=True
        )

    generated_ids = outputs.sequences[0][inputs["input_ids"].shape[1]:]
    cot_text = qwen_tokenizer.decode(generated_ids, skip_special_tokens=True)
    print(f"  CoT Length : {len(cot_text.split())} words")

    if mode in ["FULL_RDS", "ENTROPY_ONLY"]:
        logits_stack = torch.stack(outputs.scores, dim=1).squeeze(0)
        gamma_dyn, entropy = calculate_dynamic_gamma(logits_stack)
        print(f"  Entropy    : {entropy:.3f}  →  Gamma: {gamma_dyn:.3f}")
    else:
        gamma_dyn, entropy = 0.5, 0.0

    if mode in ["FULL_RDS", "GRADIENT_ONLY"]:
        sensitivities = get_gradient_sensitivity(
            cot_text, rob_tokenizer, rob_model, device, target_class=1
        )
        sorted_sens = sorted(sensitivities.items(), key=lambda x: x[1], reverse=True)
        critical_tokens = [t[0] for t in sorted_sens if len(t[0]) >= 4][:5]
        print(f"  Crit.Tokens: {critical_tokens}")
    else:
        critical_tokens = []

    return {
        "tweet": tweet,
        "cot_text": cot_text,
        "entropy": entropy,
        "gamma_dyn": gamma_dyn,
        "critical_tokens": critical_tokens,
        "mode": mode
    }

Ablation Study (Entropy Only and Gradient only)

Entropy Only

In [11]:
import torch
import pandas as pd
from IPython.display import display

CURRENT_MODE = "ENTROPY_ONLY"
NUM_SAMPLES  = 100

results_list        = []
correct_predictions = 0

print(f"🚀 Starting RDS v2 Pipeline in {CURRENT_MODE} mode...")
print(f"   Upgrades: structured verdict prompt + entropy-adaptive alpha\n")

for i in range(NUM_SAMPLES):
    sample_tweet = test_data[i]["text"]
    true_label   = test_data[i]["label"]

    # 1. Generate CoT + entropy (no gradient step in ENTROPY_ONLY)
    result_dict = generate_cot_and_analyze_v2(sample_tweet, mode=CURRENT_MODE, tweet_num=i+1)

    # 2. Compress CoT FIRST using the dynamic budget + critical-token protection
    compressed_text = compress_cot_improved(
        result_dict["cot_text"],
        result_dict["gamma_dyn"],
        result_dict["critical_tokens"]
    )

    # 3. THEN classify using the COMPRESSED CoT
    prediction, p_roberta, cot_signal, alpha, p_fused = fused_classify_v2(
        sample_tweet,
        compressed_text,            # ← was result_dict["cot_text"]
        result_dict["entropy"],
        rob_tokenizer, rob_model, device
    )

    is_correct = (prediction == true_label)
    if is_correct:
        correct_predictions += 1

    print(f"  RoBERTa={p_roberta:.3f} | CoT={cot_signal:.1f} | α={alpha:.3f} "
          f"| Fused={p_fused:.3f} | Pred={prediction} | True={true_label} "
          f"| {'✅' if is_correct else '❌'}")

    results_list.append({
        "Tweet"             : sample_tweet[:35] + "...",
        "True"              : true_label,
        "Pred"              : prediction,
        "✓?"                : "✅" if is_correct else "❌",
        "RoBERTa P(ironic)" : round(p_roberta, 3),
        "CoT Verdict"       : cot_signal,
        "α (adaptive)"      : round(alpha, 3),
        "Fused P(ironic)"   : round(p_fused, 3),
        "Entropy"           : round(result_dict["entropy"], 3),
        "Gamma"             : round(result_dict["gamma_dyn"], 3),
        "Orig Len"          : len(result_dict["cot_text"].split()),
        "Comp Len"          : len(compressed_text.split()),
    })

accuracy_pct = (correct_predictions / NUM_SAMPLES) * 100
skip_ratio   = sum(1 - r["Comp Len"]/r["Orig Len"] for r in results_list) / NUM_SAMPLES

print(f"\n{'='*64}")
print(f"🏆 RDS v2 [{CURRENT_MODE}] ACCURACY : {accuracy_pct:.1f}%  ({correct_predictions}/{NUM_SAMPLES})")
print(f"📉 Avg Token-Skip Ratio         : {skip_ratio:.1%}")
print(f"⚖️  Alpha range used             : [0.35 – 0.75] (entropy-gated)")
print(f"{'='*64}")

df = pd.DataFrame(results_list)
display(df)

🚀 Starting RDS v2 Pipeline in ENTROPY_ONLY mode...
   Upgrades: structured verdict prompt + entropy-adaptive alpha


--- Processing Tweet 1: @user Can U Help?||More conservatives needed on #TSU + get p... ---
  CoT Length : 86 words
  Entropy    : 0.339  →  Gamma: 0.468
  RoBERTa=0.303 | CoT=1.0 | α=0.689 | Fused=0.520 | Pred=1 | True=0 | ❌

--- Processing Tweet 2: Just walked in to #Starbucks and asked for a "tall blonde" H... ---
  CoT Length : 90 words
  Entropy    : 0.552  →  Gamma: 0.510
  RoBERTa=0.650 | CoT=1.0 | α=0.850 | Fused=0.702 | Pred=1 | True=1 | ✅

--- Processing Tweet 3: #NOT GONNA WIN... ---
  CoT Length : 93 words
  Entropy    : 0.533  →  Gamma: 0.507
  RoBERTa=0.033 | CoT=0.5 | α=0.850 | Fused=0.103 | Pred=0 | True=0 | ✅

--- Processing Tweet 4: @user He is exactly that sort of person. Weirdo!... ---
  CoT Length : 93 words
  Entropy    : 0.213  →  Gamma: 0.443
  RoBERTa=0.209 | CoT=0.5 | α=0.563 | Fused=0.336 | Pred=0 | True=0 | ✅

--- Processing Tweet 5: So much #sarcasm at work mate 10/10 #boring 100% #dead mate ... ---
  CoT Length : 83 words
  Entropy    : 0.456  →  Gamma: 0.491
  RoBERTa=0.075 | CoT=1.0 | α=0.806 | Fused=0.254 | Pred=0 | True=1 | ❌

--- Processing Tweet 6: Corny jokes are my absolute favorite... ---
  CoT Length : 98 words
  Entropy    : 0.366  →  Gamma: 0.473
  RoBERTa=0.981 | CoT=0.5 | α=0.716 | Fused=0.845 | Pred=1 | True=0 | ❌

--- Processing Tweet 7: People complain about my backround pic and all I feel is lik... ---
  CoT Length : 88 words
  Entropy    : 0.410  →  Gamma: 0.482
  RoBERTa=0.269 | CoT=0.5 | α=0.760 | Fused=0.325 | Pred=0 | True=1 | ❌

--- Processing Tweet 8: @user @user Darn, my sock joke needs fixing?... ---
  CoT Length : 89 words
  Entropy    : 0.334  →  Gamma: 0.467
  RoBERTa=0.090 | CoT=0.5 | α=0.684 | Fused=0.219 | Pred=0 | True=0 | ✅

--- Processing Tweet 9: if Christian expects Fifa to sleep in my bed with me tonight... ---
  CoT Length : 87 words
  Entropy    : 0.315  →  Gamma: 0.463
  RoBERTa=0.031 | CoT=0.5 | α=0.665 | Fused=0.188 | Pred=0 | True=0 | ✅

--- Processing Tweet 10: People who tell people with anxiety to "just stop worrying a... ---
  CoT Length : 97 words
  Entropy    : 0.405  →  Gamma: 0.481
  RoBERTa=0.866 | CoT=1.0 | α=0.755 | Fused=0.899 | Pred=1 | True=1 | ✅

--- Processing Tweet 11: Most important thing I've learned in school... ---
  CoT Length : 95 words
  Entropy    : 0.404  →  Gamma: 0.481
  RoBERTa=0.910 | CoT=0.5 | α=0.754 | Fused=0.809 | Pred=1 | True=0 | ❌

--- Processing Tweet 12: #OrionLaunch underway - yeah! #Orion... ---
  CoT Length : 83 words
  Entropy    : 0.437  →  Gamma: 0.487
  RoBERTa=0.359 | CoT=1.0 | α=0.787 | Fused=0.495 | Pred=0 | True=0 | ✅

--- Processing Tweet 13: I love context and large ensemble Fridays!!!!! Der my most f... ---
  CoT Length : 78 words
  Entropy    : 0.255  →  Gamma: 0.451
  RoBERTa=0.904 | CoT=1.0 | α=0.605 | Fused=0.942 | Pred=1 | True=1 | ✅

--- Processing Tweet 14: Oh boy... @user in the house. Warm up the DJ booth @user... ---
  CoT Length : 91 words
  Entropy    : 0.375  →  Gamma: 0.475
  RoBERTa=0.073 | CoT=1.0 | α=0.725 | Fused=0.328 | Pred=0 | True=0 | ✅

--- Processing Tweet 15: LIAR, i've never denied the 532 murders in Chicago in 2012 @... ---
  CoT Length : 91 words
  Entropy    : 0.331  →  Gamma: 0.466
  RoBERTa=0.059 | CoT=0.5 | α=0.681 | Fused=0.200 | Pred=0 | True=0 | ✅

--- Processing Tweet 16: Always classy, never trashy and just a little sassy.... ---
  CoT Length : 49 words
  Entropy    : 0.489  →  Gamma: 0.498
  RoBERTa=0.090 | CoT=0.5 | α=0.839 | Fused=0.157 | Pred=0 | True=0 | ✅

--- Processing Tweet 17: you believe you can say something, provide no proof and its ... ---
  CoT Length : 92 words
  Entropy    : 0.379  →  Gamma: 0.476
  RoBERTa=0.116 | CoT=0.5 | α=0.729 | Fused=0.220 | Pred=0 | True=0 | ✅

--- Processing Tweet 18: @user #Not #Long To Go #Before #MainStream #Media #Pitch. #S... ---
  CoT Length : 81 words
  Entropy    : 0.362  →  Gamma: 0.473
  RoBERTa=0.124 | CoT=1.0 | α=0.712 | Fused=0.376 | Pred=0 | True=0 | ✅

--- Processing Tweet 19: @user Re: Jamie Grace has Tourette's? Thanks for sharing. I'... ---
  CoT Length : 7 words
  Entropy    : 0.141  →  Gamma: 0.429
  RoBERTa=0.050 | CoT=1.0 | α=0.550 | Fused=0.478 | Pred=0 | True=0 | ✅

--- Processing Tweet 20: @user Guess they didn't get the memo reg non-nuclear Baltic ... ---
  CoT Length : 85 words
  Entropy    : 0.327  →  Gamma: 0.465
  RoBERTa=0.486 | CoT=0.5 | α=0.677 | Fused=0.491 | Pred=0 | True=1 | ❌

--- Processing Tweet 21: Exam na jud. Merry christmas. ||#Sarcasm|#KillUsSlowly... ---
  CoT Length : 84 words
  Entropy    : 0.424  →  Gamma: 0.485
  RoBERTa=0.155 | CoT=0.5 | α=0.774 | Fused=0.233 | Pred=0 | True=1 | ❌

--- Processing Tweet 22: The definition of #IRONY would be if a 77-year-old rapper we... ---
  CoT Length : 81 words
  Entropy    : 0.370  →  Gamma: 0.474
  RoBERTa=0.815 | CoT=1.0 | α=0.720 | Fused=0.867 | Pred=1 | True=1 | ✅

--- Processing Tweet 23: Pretty excited about how you gave up on me. File Under: #sar... ---
  CoT Length : 86 words
  Entropy    : 0.366  →  Gamma: 0.473
  RoBERTa=0.508 | CoT=1.0 | α=0.716 | Fused=0.648 | Pred=1 | True=1 | ✅

--- Processing Tweet 24: Who told the #hipsters that #irony was a thing of the Clinto... ---
  CoT Length : 89 words
  Entropy    : 0.388  →  Gamma: 0.478
  RoBERTa=0.348 | CoT=0.5 | α=0.738 | Fused=0.387 | Pred=0 | True=1 | ❌

--- Processing Tweet 25: @user u know that. How u doing??... ---
  CoT Length : 49 words
  Entropy    : 0.422  →  Gamma: 0.484
  RoBERTa=0.026 | CoT=0.5 | α=0.772 | Fused=0.134 | Pred=0 | True=0 | ✅

--- Processing Tweet 26: @user hmm... let me think about that #sarcasm... ---
  CoT Length : 87 words
  Entropy    : 0.331  →  Gamma: 0.466
  RoBERTa=0.088 | CoT=0.5 | α=0.681 | Fused=0.220 | Pred=0 | True=1 | ❌

--- Processing Tweet 27: If you wanna look like a badass, have drama on social media ... ---
  CoT Length : 6 words
  Entropy    : 0.382  →  Gamma: 0.476
  RoBERTa=0.703 | CoT=0.5 | α=0.732 | Fused=0.649 | Pred=1 | True=1 | ✅

--- Processing Tweet 28: How dare Charles Barkley have an intelligent conversation ab... ---
  CoT Length : 84 words
  Entropy    : 0.334  →  Gamma: 0.467
  RoBERTa=0.355 | CoT=1.0 | α=0.684 | Fused=0.559 | Pred=1 | True=1 | ✅

--- Processing Tweet 29: @user I think the general rule is, if it's open all night, p... ---
  CoT Length : 91 words
  Entropy    : 0.386  →  Gamma: 0.477
  RoBERTa=0.055 | CoT=0.5 | α=0.736 | Fused=0.173 | Pred=0 | True=0 | ✅

--- Processing Tweet 30: Natalie Prass - Bird of Prey: via @user... ---
  CoT Length : 87 words
  Entropy    : 0.330  →  Gamma: 0.466
  RoBERTa=0.029 | CoT=0.5 | α=0.680 | Fused=0.180 | Pred=0 | True=0 | ✅

--- Processing Tweet 31: Nooooooooooo again it's on!!! #PickANewSong #CantStandIt... ---
  CoT Length : 87 words
  Entropy    : 0.449  →  Gamma: 0.490
  RoBERTa=0.266 | CoT=0.0 | α=0.799 | Fused=0.213 | Pred=0 | True=0 | ✅

--- Processing Tweet 32: Being a hipster now is so mainstream. Oh, the irony. #hipste... ---
  CoT Length : 6 words
  Entropy    : 0.251  →  Gamma: 0.450
  RoBERTa=0.922 | CoT=1.0 | α=0.601 | Fused=0.953 | Pred=1 | True=1 | ✅

--- Processing Tweet 33: @user exactly and we are fighting like animals... ---
  CoT Length : 86 words
  Entropy    : 0.445  →  Gamma: 0.489
  RoBERTa=0.351 | CoT=0.5 | α=0.795 | Fused=0.382 | Pred=0 | True=0 | ✅

--- Processing Tweet 34: #TeenAnalCasting #Top Top 50 Christian Songs For 2012... ---
  CoT Length : 93 words
  Entropy    : 0.484  →  Gamma: 0.497
  RoBERTa=0.111 | CoT=0.0 | α=0.834 | Fused=0.093 | Pred=0 | True=0 | ✅

--- Processing Tweet 35: The girls on #SororitySisters thought they'd get rich and fa... ---
  CoT Length : 88 words
  Entropy    : 0.378  →  Gamma: 0.476
  RoBERTa=0.865 | CoT=0.5 | α=0.728 | Fused=0.766 | Pred=1 | True=0 | ❌

--- Processing Tweet 36: Speaking of #country #music albums, anyone else think #Sundo... ---
  CoT Length : 80 words
  Entropy    : 0.243  →  Gamma: 0.449
  RoBERTa=0.045 | CoT=1.0 | α=0.593 | Fused=0.434 | Pred=0 | True=0 | ✅

--- Processing Tweet 37: #TeenAnalCasting #Sex Sex and the City 2 Movie Casting Audit... ---
  CoT Length : 80 words
  Entropy    : 0.296  →  Gamma: 0.459
  RoBERTa=0.170 | CoT=1.0 | α=0.646 | Fused=0.464 | Pred=0 | True=0 | ✅

--- Processing Tweet 38: season 6 episode 3 carries outfit, simple & chic 👌... ---
  CoT Length : 84 words
  Entropy    : 0.318  →  Gamma: 0.464
  RoBERTa=0.089 | CoT=0.0 | α=0.668 | Fused=0.059 | Pred=0 | True=0 | ✅

--- Processing Tweet 39: Well got the truck buried today perfect way to start a rainy... ---
  CoT Length : 89 words
  Entropy    : 0.371  →  Gamma: 0.474
  RoBERTa=0.566 | CoT=0.5 | α=0.721 | Fused=0.547 | Pred=1 | True=1 | ✅

--- Processing Tweet 40: On the train and surrounded by posh people, I'm so at home! ... ---
  CoT Length : 92 words
  Entropy    : 0.360  →  Gamma: 0.472
  RoBERTa=0.665 | CoT=0.5 | α=0.710 | Fused=0.617 | Pred=1 | True=1 | ✅

--- Processing Tweet 41: Stupid #doctors visits is gonna bury me!! Now that's #irony... ---
  CoT Length : 6 words
  Entropy    : 0.221  →  Gamma: 0.445
  RoBERTa=0.549 | CoT=1.0 | α=0.571 | Fused=0.743 | Pred=1 | True=1 | ✅

--- Processing Tweet 42: Love the way @user says fault from last night will be fixed ... ---
  CoT Length : 92 words
  Entropy    : 0.312  →  Gamma: 0.463
  RoBERTa=0.961 | CoT=1.0 | α=0.662 | Fused=0.974 | Pred=1 | True=1 | ✅

--- Processing Tweet 43: Planning a vacation instead of studying.... My priorities ar... ---
  CoT Length : 98 words
  Entropy    : 0.328  →  Gamma: 0.466
  RoBERTa=0.624 | CoT=0.5 | α=0.678 | Fused=0.584 | Pred=1 | True=1 | ✅

--- Processing Tweet 44: Dan said he's going to have a sign for me at the airport whe... ---
  CoT Length : 91 words
  Entropy    : 0.520  →  Gamma: 0.504
  RoBERTa=0.362 | CoT=1.0 | α=0.850 | Fused=0.458 | Pred=0 | True=0 | ✅

--- Processing Tweet 45: You decide to go on vacation without me sleep? Reaaaal nice.... ---
  CoT Length : 90 words
  Entropy    : 0.303  →  Gamma: 0.461
  RoBERTa=0.188 | CoT=0.5 | α=0.653 | Fused=0.296 | Pred=0 | True=1 | ❌

--- Processing Tweet 46: @user No sugar during christmas time? :(... ---
  CoT Length : 92 words
  Entropy    : 0.339  →  Gamma: 0.468
  RoBERTa=0.125 | CoT=0.5 | α=0.689 | Fused=0.242 | Pred=0 | True=0 | ✅

--- Processing Tweet 47: Can't wait to have an afternoon schedule because of you. It'... ---
  CoT Length : 71 words
  Entropy    : 0.418  →  Gamma: 0.484
  RoBERTa=0.970 | CoT=1.0 | α=0.768 | Fused=0.977 | Pred=1 | True=1 | ✅

--- Processing Tweet 48: @user 180 dead on 26/11 n more than 10k our ppl killed in te... ---
  CoT Length : 77 words
  Entropy    : 0.280  →  Gamma: 0.456
  RoBERTa=0.286 | CoT=1.0 | α=0.630 | Fused=0.550 | Pred=1 | True=1 | ✅

--- Processing Tweet 49: the ONLY time a crime becomes a federal crime @user @user @u... ---
  CoT Length : 7 words
  Entropy    : 0.062  →  Gamma: 0.414
  RoBERTa=0.090 | CoT=1.0 | α=0.550 | Fused=0.500 | Pred=0 | True=0 | ✅

--- Processing Tweet 50: this music is for the people and not for the money. peace an... ---
  CoT Length : 94 words
  Entropy    : 0.526  →  Gamma: 0.505
  RoBERTa=0.101 | CoT=1.0 | α=0.850 | Fused=0.236 | Pred=0 | True=0 | ✅

--- Processing Tweet 51: Rangers league game with Alloa moved because of the Petrofac... ---
  CoT Length : 6 words
  Entropy    : 0.121  →  Gamma: 0.425
  RoBERTa=0.565 | CoT=1.0 | α=0.550 | Fused=0.761 | Pred=1 | True=1 | ✅

--- Processing Tweet 52: How to Find a Life Coach (& the questions you need to ask be... ---
  CoT Length : 99 words
  Entropy    : 0.303  →  Gamma: 0.461
  RoBERTa=0.033 | CoT=0.5 | α=0.653 | Fused=0.195 | Pred=0 | True=0 | ✅

--- Processing Tweet 53: I wonder what was the holiday rituals for true Africans... ---
  CoT Length : 87 words
  Entropy    : 0.432  →  Gamma: 0.486
  RoBERTa=0.209 | CoT=0.5 | α=0.782 | Fused=0.272 | Pred=0 | True=0 | ✅

--- Processing Tweet 54: Been at the ER now since 10... #yay #not... ---
  CoT Length : 89 words
  Entropy    : 0.331  →  Gamma: 0.466
  RoBERTa=0.344 | CoT=0.5 | α=0.681 | Fused=0.394 | Pred=0 | True=1 | ❌

--- Processing Tweet 55: @user Suhs been clean for 2 years and has only been in the l... ---
  CoT Length : 91 words
  Entropy    : 0.306  →  Gamma: 0.461
  RoBERTa=0.041 | CoT=0.5 | α=0.656 | Fused=0.199 | Pred=0 | True=0 | ✅

--- Processing Tweet 56: @user @user thank you studs for perfecting and teaching my b... ---
  CoT Length : 78 words
  Entropy    : 0.526  →  Gamma: 0.505
  RoBERTa=0.643 | CoT=0.5 | α=0.850 | Fused=0.621 | Pred=1 | True=0 | ❌

--- Processing Tweet 57: Haley approves of her new hammock 🐭 #ratsofinstagram... ---
  CoT Length : 94 words
  Entropy    : 0.400  →  Gamma: 0.480
  RoBERTa=0.187 | CoT=0.5 | α=0.750 | Fused=0.265 | Pred=0 | True=0 | ✅

--- Processing Tweet 58: 30 years on, people still haven't got justice they deserve. ... ---
  CoT Length : 86 words
  Entropy    : 0.439  →  Gamma: 0.488
  RoBERTa=0.915 | CoT=1.0 | α=0.789 | Fused=0.933 | Pred=1 | True=1 | ✅

--- Processing Tweet 59: Pips who drop out of school n have Kirya as 'eir role model ... ---
  CoT Length : 84 words
  Entropy    : 0.383  →  Gamma: 0.477
  RoBERTa=0.289 | CoT=1.0 | α=0.733 | Fused=0.479 | Pred=0 | True=0 | ✅

--- Processing Tweet 60: Free Pets and Animals Books #freebiebookdownload #Pets... ---
  CoT Length : 6 words
  Entropy    : 0.328  →  Gamma: 0.466
  RoBERTa=0.155 | CoT=0.5 | α=0.678 | Fused=0.266 | Pred=0 | True=0 | ✅

--- Processing Tweet 61: @user There will be no next employer in NFL for Trestman. He... ---
  CoT Length : 91 words
  Entropy    : 0.392  →  Gamma: 0.478
  RoBERTa=0.081 | CoT=0.5 | α=0.742 | Fused=0.189 | Pred=0 | True=0 | ✅

--- Processing Tweet 62: Loooovvveeeeeee when my phone gets wiped -.- #not... ---
  CoT Length : 95 words
  Entropy    : 0.504  →  Gamma: 0.501
  RoBERTa=0.306 | CoT=0.0 | α=0.850 | Fused=0.260 | Pred=0 | True=1 | ❌

--- Processing Tweet 63: Painting all cops with a broad brush because of the actions ... ---
  CoT Length : 6 words
  Entropy    : 0.173  →  Gamma: 0.435
  RoBERTa=0.861 | CoT=1.0 | α=0.550 | Fused=0.924 | Pred=1 | True=1 | ✅

--- Processing Tweet 64: Don't know if I can handle this crazy 11-2 shift. It's so lo... ---
  CoT Length : 73 words
  Entropy    : 0.378  →  Gamma: 0.476
  RoBERTa=0.084 | CoT=1.0 | α=0.728 | Fused=0.333 | Pred=0 | True=1 | ❌

--- Processing Tweet 65: I just love being ignored😊|#not😒... ---
  CoT Length : 83 words
  Entropy    : 0.392  →  Gamma: 0.478
  RoBERTa=0.180 | CoT=1.0 | α=0.742 | Fused=0.392 | Pred=0 | True=1 | ❌

--- Processing Tweet 66: #Irony RT @user If you're going to give someone a scathing, ... ---
  CoT Length : 94 words
  Entropy    : 0.379  →  Gamma: 0.476
  RoBERTa=0.295 | CoT=0.5 | α=0.729 | Fused=0.350 | Pred=0 | True=1 | ❌

--- Processing Tweet 67: Produce Mobile Apps #not... ---
  CoT Length : 87 words
  Entropy    : 0.340  →  Gamma: 0.468
  RoBERTa=0.319 | CoT=0.5 | α=0.690 | Fused=0.375 | Pred=0 | True=1 | ❌

--- Processing Tweet 68: Decide that you want it more than you are afraid of it. -Bil... ---
  CoT Length : 90 words
  Entropy    : 0.277  →  Gamma: 0.456
  RoBERTa=0.077 | CoT=0.5 | α=0.627 | Fused=0.235 | Pred=0 | True=1 | ❌

--- Processing Tweet 69: Finally finished the first season of #VeronicaMars. Move ove... ---
  CoT Length : 77 words
  Entropy    : 0.297  →  Gamma: 0.460
  RoBERTa=0.103 | CoT=1.0 | α=0.647 | Fused=0.419 | Pred=0 | True=0 | ✅

--- Processing Tweet 70: Merry Christmas to all those soldiers out there that couldn'... ---
  CoT Length : 92 words
  Entropy    : 0.373  →  Gamma: 0.475
  RoBERTa=0.041 | CoT=0.5 | α=0.723 | Fused=0.168 | Pred=0 | True=0 | ✅

--- Processing Tweet 71: About as relevant as Michael Sam and Jason Collins. RT @user... ---
  CoT Length : 86 words
  Entropy    : 0.343  →  Gamma: 0.469
  RoBERTa=0.788 | CoT=1.0 | α=0.693 | Fused=0.853 | Pred=1 | True=0 | ❌

--- Processing Tweet 72: Getting Final Jeopardy correct on Kids Jeopardy boosts my se... ---
  CoT Length : 93 words
  Entropy    : 0.523  →  Gamma: 0.505
  RoBERTa=0.966 | CoT=0.5 | α=0.850 | Fused=0.896 | Pred=1 | True=0 | ❌

--- Processing Tweet 73: itsfunny bc people think im quiet|but im just listening toev... ---
  CoT Length : 94 words
  Entropy    : 0.307  →  Gamma: 0.461
  RoBERTa=0.093 | CoT=1.0 | α=0.657 | Fused=0.404 | Pred=0 | True=1 | ❌

--- Processing Tweet 74: Woke Up , showered , made a lunch and got ready for work onl... ---
  CoT Length : 55 words
  Entropy    : 0.352  →  Gamma: 0.470
  RoBERTa=0.603 | CoT=0.5 | α=0.702 | Fused=0.572 | Pred=1 | True=0 | ❌

--- Processing Tweet 75: @user @user @user @user @user How many of those jobs earn #m... ---
  CoT Length : 88 words
  Entropy    : 0.428  →  Gamma: 0.486
  RoBERTa=0.096 | CoT=1.0 | α=0.778 | Fused=0.297 | Pred=0 | True=0 | ✅

--- Processing Tweet 76: I reckon straight women fancy victoria secret models more th... ---
  CoT Length : 99 words
  Entropy    : 0.265  →  Gamma: 0.453
  RoBERTa=0.879 | CoT=0.5 | α=0.615 | Fused=0.733 | Pred=1 | True=1 | ✅

--- Processing Tweet 77: Incredible insight on the @user #bornrisky campaign: #ampute... ---
  CoT Length : 84 words
  Entropy    : 0.292  →  Gamma: 0.459
  RoBERTa=0.311 | CoT=1.0 | α=0.642 | Fused=0.558 | Pred=1 | True=0 | ❌

--- Processing Tweet 78: Love #hiphop mix tapes or have a mixtape to promote check ou... ---
  CoT Length : 82 words
  Entropy    : 0.312  →  Gamma: 0.462
  RoBERTa=0.057 | CoT=0.5 | α=0.662 | Fused=0.206 | Pred=0 | True=0 | ✅

--- Processing Tweet 79: Extended cut "NICHA" #trailer #spoof #film #dramatic #action... ---
  CoT Length : 86 words
  Entropy    : 0.360  →  Gamma: 0.472
  RoBERTa=0.210 | CoT=1.0 | α=0.710 | Fused=0.439 | Pred=0 | True=0 | ✅

--- Processing Tweet 80: @user Stunning work. #british #textiles #footwear #madeinbri... ---
  CoT Length : 92 words
  Entropy    : 0.535  →  Gamma: 0.507
  RoBERTa=0.378 | CoT=0.5 | α=0.850 | Fused=0.396 | Pred=0 | True=0 | ✅

--- Processing Tweet 81: @user @user Sent it but too slow. I had already posted.... ---
  CoT Length : 65 words
  Entropy    : 0.448  →  Gamma: 0.490
  RoBERTa=0.046 | CoT=0.0 | α=0.798 | Fused=0.036 | Pred=0 | True=0 | ✅

--- Processing Tweet 82: #FEMALECONDOM #anally #vaginally #prevent STD's/HIV/pregnanc... ---
  CoT Length : 7 words
  Entropy    : 0.088  →  Gamma: 0.419
  RoBERTa=0.160 | CoT=1.0 | α=0.550 | Fused=0.538 | Pred=1 | True=0 | ❌

--- Processing Tweet 83: Little cutie #Chico #Dog #Doggy #Puppy #Sweet #Cute #UK #Bla... ---
  CoT Length : 49 words
  Entropy    : 0.268  →  Gamma: 0.454
  RoBERTa=0.092 | CoT=0.0 | α=0.618 | Fused=0.057 | Pred=0 | True=0 | ✅

--- Processing Tweet 84: @user Niagra Falls tho... Really? #irony #LOL... ---
  CoT Length : 82 words
  Entropy    : 0.318  →  Gamma: 0.464
  RoBERTa=0.217 | CoT=0.5 | α=0.668 | Fused=0.311 | Pred=0 | True=1 | ❌

--- Processing Tweet 85: If we win against Poland and Scotland, does that put us 65th... ---
  CoT Length : 57 words
  Entropy    : 0.390  →  Gamma: 0.478
  RoBERTa=0.114 | CoT=1.0 | α=0.740 | Fused=0.344 | Pred=0 | True=1 | ❌

--- Processing Tweet 86: #Myanmar #men #plead #not #guilty to #murder of #British #to... ---
  CoT Length : 80 words
  Entropy    : 0.217  →  Gamma: 0.444
  RoBERTa=0.209 | CoT=0.5 | α=0.567 | Fused=0.335 | Pred=0 | True=0 | ✅

--- Processing Tweet 87: Since the tribunal was established 14 years ago, no complain... ---
  CoT Length : 90 words
  Entropy    : 0.232  →  Gamma: 0.447
  RoBERTa=0.561 | CoT=1.0 | α=0.582 | Fused=0.744 | Pred=1 | True=1 | ✅

--- Processing Tweet 88: @user Garner protesters chant 'F*ck Fox News' despite Fox ag... ---
  CoT Length : 82 words
  Entropy    : 0.375  →  Gamma: 0.475
  RoBERTa=0.812 | CoT=1.0 | α=0.725 | Fused=0.864 | Pred=1 | True=1 | ✅

--- Processing Tweet 89: @user After 1989, why did NATO need to expand?... ---
  CoT Length : 83 words
  Entropy    : 0.266  →  Gamma: 0.453
  RoBERTa=0.169 | CoT=0.5 | α=0.616 | Fused=0.296 | Pred=0 | True=0 | ✅


,Tweet,True,Pred,✓?,RoBERTa P(ironic),CoT Verdict,α (adaptive),Fused P(ironic),Entropy,Gamma,Orig Len,Comp Len
0,@user Can U Help?||More conservativ...,0,1,❌,0.303,1.0,0.689,0.520,0.339,0.468,86,45
1,Just walked in to #Starbucks and as...,1,1,✅,0.650,1.0,0.850,0.702,0.552,0.510,90,44
2,#NOT GONNA WIN...,0,0,✅,0.033,0.5,0.850,0.103,0.533,0.507,93,45
3,@user He is exactly that sort of pe...,0,0,✅,0.209,0.5,0.563,0.336,0.213,0.443,93,51
4,So much #sarcasm at work mate 10/10...,1,0,❌,0.075,1.0,0.806,0.254,0.456,0.491,83,42
...,...,...,...,...,...,...,...,...,...,...,...,...
95,The last day of the year and I will...,0,0,✅,0.133,1.0,0.747,0.352,0.397,0.479,84,43
96,MB forgot to move the elf on shelf ...,0,1,❌,0.629,1.0,0.710,0.737,0.360,0.472,84,44
97,"@user happy new year, da! Thanks so...",0,0,✅,0.095,0.5,0.748,0.198,0.398,0.480,99,51
98,WATCH: #Megatron from #Transformers...,0,1,❌,0.515,0.5,0.722,0.511,0.372,0.474,87,45
99,@user @user #not #working when are ...,0,0,✅,0.075,0.5,0.675,0.213,0.325,0.465,87,46

Gradient Only

In [12]:
import torch
import pandas as pd
from IPython.display import display

CURRENT_MODE = "GRADIENT_ONLY"
NUM_SAMPLES  = 100

results_list        = []
correct_predictions = 0

print(f"🚀 Starting RDS v2 Pipeline in {CURRENT_MODE} mode...")
print(f"   Upgrades: structured verdict prompt + entropy-adaptive alpha\n")

for i in range(NUM_SAMPLES):
    sample_tweet = test_data[i]["text"]
    true_label   = test_data[i]["label"]

    # 1. Generate CoT + gradient step (no entropy in GRADIENT_ONLY)
    result_dict = generate_cot_and_analyze_v2(sample_tweet, mode=CURRENT_MODE)

    # 2. Compress CoT FIRST using the dynamic budget + critical-token protection
    #    Note: entropy=0.0 in GRADIENT_ONLY → alpha defaults to alpha_low (0.35)
    #    meaning CoT verdict gets maximum weight in this mode
    compressed_text = compress_cot_improved(
        result_dict["cot_text"],
        result_dict["gamma_dyn"],
        result_dict["critical_tokens"]
    )

    # 3. THEN classify using the COMPRESSED CoT
    prediction, p_roberta, cot_signal, alpha, p_fused = fused_classify_v2(
        sample_tweet,
        compressed_text,            # ← was result_dict["cot_text"]
        result_dict["entropy"],
        rob_tokenizer, rob_model, device
    )

    is_correct = (prediction == true_label)
    if is_correct:
        correct_predictions += 1

    print(f"  RoBERTa={p_roberta:.3f} | CoT={cot_signal:.1f} | α={alpha:.3f} "
          f"| Fused={p_fused:.3f} | Pred={prediction} | True={true_label} "
          f"| {'✅' if is_correct else '❌'}")

    results_list.append({
        "Tweet"             : sample_tweet[:35] + "...",
        "True"              : true_label,
        "Pred"              : prediction,
        "✓?"                : "✅" if is_correct else "❌",
        "RoBERTa P(ironic)" : round(p_roberta, 3),
        "CoT Verdict"       : cot_signal,
        "α (adaptive)"      : round(alpha, 3),
        "Fused P(ironic)"   : round(p_fused, 3),
        "Entropy"           : round(result_dict["entropy"], 3),
        "Gamma"             : round(result_dict["gamma_dyn"], 3),
        "Orig Len"          : len(result_dict["cot_text"].split()),
        "Comp Len"          : len(compressed_text.split()),
        "Critical Tokens"   : str(result_dict["critical_tokens"]),
    })

accuracy_pct = (correct_predictions / NUM_SAMPLES) * 100
skip_ratio   = sum(1 - r["Comp Len"]/r["Orig Len"] for r in results_list) / NUM_SAMPLES

print(f"\n{'='*64}")
print(f"🏆 RDS v2 [{CURRENT_MODE}] ACCURACY : {accuracy_pct:.1f}%  ({correct_predictions}/{NUM_SAMPLES})")
print(f"📉 Avg Token-Skip Ratio         : {skip_ratio:.1%}")
print(f"⚖️  Alpha range used             : [0.35 – 0.75] (entropy-gated)")
print(f"{'='*64}")

df = pd.DataFrame(results_list)
display(df)

🚀 Starting RDS v2 Pipeline in GRADIENT_ONLY mode...
   Upgrades: structured verdict prompt + entropy-adaptive alpha


--- Processing Tweet: @user Can U Help?||More conservatives needed on #TSU + get p... ---
  CoT Length : 61 words
  Crit.Tokens: ['PROG', 'difference', 'groups', 'make', 'doing']
  RoBERTa=0.303 | CoT=0.5 | α=0.550 | Fused=0.392 | Pred=0 | True=0 | ✅

--- Processing Tweet: Just walked in to #Starbucks and asked for a "tall blonde" H... ---
  CoT Length : 92 words
  Crit.Tokens: ['expresses', 'dict', 'nonsensical', 'ironic', 'irony']
  RoBERTa=0.650 | CoT=1.0 | α=0.550 | Fused=0.807 | Pred=1 | True=1 | ✅

--- Processing Tweet: #NOT GONNA WIN... ---
  CoT Length : 96 words
  Crit.Tokens: ['their', 'Step', 'hashtag', 'feelings', 'happy']
  RoBERTa=0.033 | CoT=0.5 | α=0.550 | Fused=0.243 | Pred=0 | True=0 | ✅

--- Processing Tweet: @user He is exactly that sort of person. Weirdo!... ---
  CoT Length : 94 words
  Crit.Tokens: ['Analysis', 'Context', 'general', 'Content', 'ironic']
  RoBERTa=0.209 | CoT=0.5 | α=0.550 | Fused=0.340 | Pred=0 | True=0 | ✅

--- Processing Tweet: So much #sarcasm at work mate 10/10 #boring 100% #dead mate ... ---
  CoT Length : 79 words
  Crit.Tokens: ['work', 'ironic', 'acknowledging', 'atmosphere', 'dict']
  RoBERTa=0.075 | CoT=1.0 | α=0.550 | Fused=0.491 | Pred=0 | True=1 | ❌

--- Processing Tweet: Corny jokes are my absolute favorite... ---
  CoT Length : 89 words
  Crit.Tokens: ['emphasizes', 'contradicts', 'life', 'However', 'suggests']
  RoBERTa=0.981 | CoT=0.0 | α=0.550 | Fused=0.540 | Pred=1 | True=0 | ❌

--- Processing Tweet: People complain about my backround pic and all I feel is lik... ---
  CoT Length : 94 words
  Crit.Tokens: ['Step', 'There', 'Ident', 'indication', 'irony']
  RoBERTa=0.269 | CoT=0.5 | α=0.550 | Fused=0.373 | Pred=0 | True=1 | ❌

--- Processing Tweet: @user @user Darn, my sock joke needs fixing?... ---
  CoT Length : 29 words
  Crit.Tokens: ['dict', 'They', 'unaware', 'user', 'socks']
  RoBERTa=0.090 | CoT=0.5 | α=0.550 | Fused=0.274 | Pred=0 | True=0 | ✅

--- Processing Tweet: if Christian expects Fifa to sleep in my bed with me tonight... ---
  CoT Length : 87 words
  Crit.Tokens: ['Tone', 'Context', 'Christian', 'Content', 'Interpret']
  RoBERTa=0.031 | CoT=0.0 | α=0.550 | Fused=0.017 | Pred=0 | True=0 | ✅

--- Processing Tweet: People who tell people with anxiety to "just stop worrying a... ---
  CoT Length : 96 words
  Crit.Tokens: ['Iron', 'disapproval', 'expressing', 'occurs', 'expresses']
  RoBERTa=0.866 | CoT=0.5 | α=0.550 | Fused=0.701 | Pred=1 | True=1 | ✅

--- Processing Tweet: Most important thing I've learned in school... ---
  CoT Length : 47 words
  Crit.Tokens: ['dict', 'teacher', 'empathy', 'kindness', 'lesson']
  RoBERTa=0.910 | CoT=0.0 | α=0.550 | Fused=0.500 | Pred=1 | True=0 | ❌

--- Processing Tweet: #OrionLaunch underway - yeah! #Orion... ---
  CoT Length : 93 words
  Crit.Tokens: ['Step', 'straightforward', 'excitement', 'rocket', 'enthusiasm']
  RoBERTa=0.359 | CoT=0.5 | α=0.550 | Fused=0.423 | Pred=0 | True=0 | ✅

--- Processing Tweet: I love context and large ensemble Fridays!!!!! Der my most f... ---
  CoT Length : 78 words
  Crit.Tokens: ['dict', 'ensemble', 'suggests', 'implies', 'Fridays']
  RoBERTa=0.904 | CoT=1.0 | α=0.550 | Fused=0.947 | Pred=1 | True=1 | ✅

--- Processing Tweet: Oh boy... @user in the house. Warm up the DJ booth @user... ---
  CoT Length : 5 words
  Crit.Tokens: ['dict', 'LINE']
  RoBERTa=0.073 | CoT=1.0 | α=0.550 | Fused=0.490 | Pred=0 | True=0 | ✅

--- Processing Tweet: LIAR, i've never denied the 532 murders in Chicago in 2012 @... ---
  CoT Length : 82 words
  Crit.Tokens: ['Iron', 'Step', 'irony', '2012', 'occurs']
  RoBERTa=0.059 | CoT=1.0 | α=0.550 | Fused=0.483 | Pred=0 | True=0 | ✅

--- Processing Tweet: Always classy, never trashy and just a little sassy.... ---
  CoT Length : 47 words
  Crit.Tokens: ['irony', 'dict', 'assy', 'classy', 'characteristics']
  RoBERTa=0.090 | CoT=0.0 | α=0.550 | Fused=0.050 | Pred=0 | True=0 | ✅

--- Processing Tweet: you believe you can say something, provide no proof and its ... ---
  CoT Length : 94 words
  Crit.Tokens: ['within', 'This', 'addressing', 'indicates', 'ironic']
  RoBERTa=0.116 | CoT=0.5 | α=0.550 | Fused=0.289 | Pred=0 | True=0 | ✅

--- Processing Tweet: @user #Not #Long To Go #Before #MainStream #Media #Pitch. #S... ---
  CoT Length : 83 words
  Crit.Tokens: ['Step', 'irony', 'contains', 'itch', 'Stream']
  RoBERTa=0.124 | CoT=1.0 | α=0.550 | Fused=0.518 | Pred=1 | True=0 | ❌

--- Processing Tweet: @user Re: Jamie Grace has Tourette's? Thanks for sharing. I'... ---
  CoT Length : 87 words
  Crit.Tokens: ['implying', 'implies', 'Step', 'believe', 'Gospel']
  RoBERTa=0.050 | CoT=1.0 | α=0.550 | Fused=0.478 | Pred=0 | True=0 | ✅

--- Processing Tweet: @user Guess they didn't get the memo reg non-nuclear Baltic ... ---
  CoT Length : 88 words
  Crit.Tokens: ['ironic', 'nuclear', 'irony', 'indicates', 'Step']
  RoBERTa=0.486 | CoT=0.5 | α=0.550 | Fused=0.492 | Pred=0 | True=1 | ❌

--- Processing Tweet: Exam na jud. Merry christmas. ||#Sarcasm|#KillUsSlowly... ---
  CoT Length : 93 words
  Crit.Tokens: ['combination', 'irony', 'involves', 'unpleasant', 'case']
  RoBERTa=0.155 | CoT=0.5 | α=0.550 | Fused=0.310 | Pred=0 | True=1 | ❌

--- Processing Tweet: The definition of #IRONY would be if a 77-year-old rapper we... ---
  CoT Length : 80 words
  Crit.Tokens: ['Step', 'dict', 'twist', 'discusses', 'irony']
  RoBERTa=0.815 | CoT=1.0 | α=0.550 | Fused=0.898 | Pred=1 | True=1 | ✅

--- Processing Tweet: Pretty excited about how you gave up on me. File Under: #sar... ---
  CoT Length : 90 words
  Crit.Tokens: ['dict', 'Step', 'implies', 'excited', 'irony']
  RoBERTa=0.508 | CoT=1.0 | α=0.550 | Fused=0.730 | Pred=1 | True=1 | ✅

--- Processing Tweet: Who told the #hipsters that #irony was a thing of the Clinto... ---
  CoT Length : 94 words
  Crit.Tokens: ['Step', 'history', 'suggests', 'ironic', 'assertion']
  RoBERTa=0.348 | CoT=0.5 | α=0.550 | Fused=0.416 | Pred=0 | True=1 | ❌

--- Processing Tweet: @user u know that. How u doing??... ---
  CoT Length : 94 words
  Crit.Tokens: ['However', 'greeting', 'inquire', 'ironic', 'typical']
  RoBERTa=0.026 | CoT=0.5 | α=0.550 | Fused=0.239 | Pred=0 | True=0 | ✅

--- Processing Tweet: @user hmm... let me think about that #sarcasm... ---
  CoT Length : 6 words
  Crit.Tokens: ['RESP', 'dict', 'ONLY']
  RoBERTa=0.088 | CoT=0.5 | α=0.550 | Fused=0.274 | Pred=0 | True=1 | ❌

--- Processing Tweet: If you wanna look like a badass, have drama on social media ... ---
  CoT Length : 66 words
  Crit.Tokens: ['badass', 'dict', 'emphasizes', 'contradiction', 'ironic']
  RoBERTa=0.703 | CoT=1.0 | α=0.550 | Fused=0.837 | Pred=1 | True=1 | ✅

--- Processing Tweet: How dare Charles Barkley have an intelligent conversation ab... ---
  CoT Length : 92 words
  Crit.Tokens: ['ironic', 'dict', 'race', 'This', 'indicates']
  RoBERTa=0.355 | CoT=1.0 | α=0.550 | Fused=0.646 | Pred=1 | True=1 | ✅

--- Processing Tweet: @user I think the general rule is, if it's open all night, p... ---
  CoT Length : 95 words
  Crit.Tokens: ['irony', 'dict', 'addressed', 'imply', 'Step']
  RoBERTa=0.055 | CoT=1.0 | α=0.550 | Fused=0.480 | Pred=0 | True=0 | ✅

--- Processing Tweet: Natalie Prass - Bird of Prey: via @user... ---
  CoT Length : 61 words
  Crit.Tokens: ['dict', 'irony', 'neutral', 'interaction', 'irds']
  RoBERTa=0.029 | CoT=0.0 | α=0.550 | Fused=0.016 | Pred=0 | True=0 | ✅

--- Processing Tweet: Nooooooooooo again it's on!!! #PickANewSong #CantStandIt... ---
  CoT Length : 87 words
  Crit.Tokens: ['etition', 'irony', 'Tone', 'Content', 'indicates']
  RoBERTa=0.266 | CoT=0.5 | α=0.550 | Fused=0.371 | Pred=0 | True=0 | ✅

--- Processing Tweet: Being a hipster now is so mainstream. Oh, the irony. #hipste... ---
  CoT Length : 76 words
  Crit.Tokens: ['Therefore', 'dict', 'tone', 'creates', 'indeed']
  RoBERTa=0.922 | CoT=1.0 | α=0.550 | Fused=0.957 | Pred=1 | True=1 | ✅

--- Processing Tweet: @user exactly and we are fighting like animals... ---
  CoT Length : 87 words
  Crit.Tokens: ['irony', 'implies', 'actly', 'user', 'analyze']
  RoBERTa=0.351 | CoT=0.5 | α=0.550 | Fused=0.418 | Pred=0 | True=0 | ✅

--- Processing Tweet: #TeenAnalCasting #Top Top 50 Christian Songs For 2012... ---
  CoT Length : 86 words
  Crit.Tokens: ['reacting', 'positively', 'author', 'describes', 'initial']
  RoBERTa=0.111 | CoT=0.5 | α=0.550 | Fused=0.286 | Pred=0 | True=0 | ✅

--- Processing Tweet: The girls on #SororitySisters thought they'd get rich and fa... ---
  CoT Length : 87 words
  Crit.Tokens: ['likely', 'ironic', 'dict', 'expectation', 'However']
  RoBERTa=0.865 | CoT=1.0 | α=0.550 | Fused=0.926 | Pred=1 | True=0 | ❌

--- Processing Tweet: Speaking of #country #music albums, anyone else think #Sundo... ---
  CoT Length : 59 words
  Crit.Tokens: ['dict', 'ironic', 'expresses', 'curiosity', 'Therefore']
  RoBERTa=0.045 | CoT=0.0 | α=0.550 | Fused=0.025 | Pred=0 | True=0 | ✅

--- Processing Tweet: #TeenAnalCasting #Sex Sex and the City 2 Movie Casting Audit... ---
  CoT Length : 78 words
  Crit.Tokens: ['dict', 'paradox', 'situation', 'makes', 'creates']
  RoBERTa=0.170 | CoT=1.0 | α=0.550 | Fused=0.544 | Pred=1 | True=0 | ❌

--- Processing Tweet: season 6 episode 3 carries outfit, simple & chic 👌... ---
  CoT Length : 87 words
  Crit.Tokens: ['dict', 'ironic', 'Step', 'indication', 'thinking']
  RoBERTa=0.089 | CoT=0.0 | α=0.550 | Fused=0.049 | Pred=0 | True=0 | ✅

--- Processing Tweet: Well got the truck buried today perfect way to start a rainy... ---
  CoT Length : 96 words
  Crit.Tokens: ['severity', 'perfect', 'desirable', 'further', 'ironic']
  RoBERTa=0.566 | CoT=0.5 | α=0.550 | Fused=0.536 | Pred=1 | True=1 | ✅

--- Processing Tweet: On the train and surrounded by posh people, I'm so at home! ... ---
  CoT Length : 88 words
  Crit.Tokens: ['usage', 'further', 'hasht', 'Consider', 'conveyed']
  RoBERTa=0.665 | CoT=0.5 | α=0.550 | Fused=0.591 | Pred=1 | True=1 | ✅

--- Processing Tweet: Stupid #doctors visits is gonna bury me!! Now that's #irony... ---
  CoT Length : 81 words
  Crit.Tokens: ['However', 'dict', 'irony', 'ironic', 'bury']
  RoBERTa=0.549 | CoT=1.0 | α=0.550 | Fused=0.752 | Pred=1 | True=1 | ✅

--- Processing Tweet: Love the way @user says fault from last night will be fixed ... ---
  CoT Length : 87 words
  Crit.Tokens: ['irony', 'Step', 'Ident', 'dict', 'situation']
  RoBERTa=0.961 | CoT=1.0 | α=0.550 | Fused=0.979 | Pred=1 | True=1 | ✅

--- Processing Tweet: Planning a vacation instead of studying.... My priorities ar... ---
  CoT Length : 6 words
  Crit.Tokens: ['dict', 'RESP', 'ONLY']
  RoBERTa=0.624 | CoT=0.5 | α=0.550 | Fused=0.568 | Pred=1 | True=1 | ✅

--- Processing Tweet: Dan said he's going to have a sign for me at the airport whe... ---
  CoT Length : 84 words
  Crit.Tokens: ['indicators', 'tweet', 'Step', 'dict', 'ironic']
  RoBERTa=0.362 | CoT=1.0 | α=0.550 | Fused=0.649 | Pred=1 | True=0 | ❌

--- Processing Tweet: You decide to go on vacation without me sleep? Reaaaal nice.... ---
  CoT Length : 86 words
  Crit.Tokens: ['indicators', 'implies', 'sleep', 'Step', 'nice']
  RoBERTa=0.188 | CoT=0.5 | α=0.550 | Fused=0.328 | Pred=0 | True=1 | ❌

--- Processing Tweet: @user No sugar during christmas time? :(... ---
  CoT Length : 96 words
  Crit.Tokens: ['Iron', 'involves', 'Step', 'dietary', 'sugar']
  RoBERTa=0.125 | CoT=0.5 | α=0.550 | Fused=0.294 | Pred=0 | True=0 | ✅

--- Processing Tweet: Can't wait to have an afternoon schedule because of you. It'... ---
  CoT Length : 91 words
  Crit.Tokens: ['irony', 'contradiction', 'paradox', 'Step', 'excited']
  RoBERTa=0.970 | CoT=0.5 | α=0.550 | Fused=0.759 | Pred=1 | True=1 | ✅

--- Processing Tweet: @user 180 dead on 26/11 n more than 10k our ppl killed in te... ---
  CoT Length : 77 words
  Crit.Tokens: ['Analysis', 'ironic', 'Content', 'irony', 'statement']
  RoBERTa=0.286 | CoT=0.5 | α=0.550 | Fused=0.382 | Pred=0 | True=1 | ❌

--- Processing Tweet: the ONLY time a crime becomes a federal crime @user @user @u... ---
  CoT Length : 102 words
  Crit.Tokens: ['ironic', 'irony', 'observation', 'interpreted', 'Deter']
  RoBERTa=0.090 | CoT=0.5 | α=0.550 | Fused=0.275 | Pred=0 | True=0 | ✅

--- Processing Tweet: this music is for the people and not for the money. peace an... ---
  CoT Length : 84 words
  Crit.Tokens: ['king', 'consistent', 'ironic', 'dict', 'While']
  RoBERTa=0.101 | CoT=0.0 | α=0.550 | Fused=0.055 | Pred=0 | True=0 | ✅

--- Processing Tweet: Rangers league game with Alloa moved because of the Petrofac... ---
  CoT Length : 6 words
  Crit.Tokens: ['dict', 'RESP', 'ONLY']
  RoBERTa=0.565 | CoT=0.5 | α=0.550 | Fused=0.536 | Pred=1 | True=1 | ✅

--- Processing Tweet: How to Find a Life Coach (& the questions you need to ask be... ---
  CoT Length : 40 words
  Crit.Tokens: ['dict', 'However', 'process', 'coach', 'neutral']
  RoBERTa=0.033 | CoT=0.5 | α=0.550 | Fused=0.243 | Pred=0 | True=0 | ✅

--- Processing Tweet: I wonder what was the holiday rituals for true Africans... ---
  CoT Length : 60 words
  Crit.Tokens: ['dict', 'ironic', 'critic', 'implies', 'skepticism']
  RoBERTa=0.209 | CoT=1.0 | α=0.550 | Fused=0.565 | Pred=1 | True=0 | ❌

--- Processing Tweet: Been at the ER now since 10... #yay #not... ---
  CoT Length : 83 words
  Crit.Tokens: ['generally', 'conve', 'user', 'excitement', 'However']
  RoBERTa=0.344 | CoT=0.5 | α=0.550 | Fused=0.414 | Pred=0 | True=1 | ❌

--- Processing Tweet: @user Suhs been clean for 2 years and has only been in the l... ---
  CoT Length : 79 words
  Crit.Tokens: ['irony', 'dict', 'substances', 'ironic', 'comparing']
  RoBERTa=0.041 | CoT=1.0 | α=0.550 | Fused=0.472 | Pred=0 | True=0 | ✅

--- Processing Tweet: @user @user thank you studs for perfecting and teaching my b... ---
  CoT Length : 84 words
  Crit.Tokens: ['thanking', 'suggests', 'compliment', 'Analysis', 'Content']
  RoBERTa=0.643 | CoT=0.5 | α=0.550 | Fused=0.579 | Pred=1 | True=0 | ❌

--- Processing Tweet: Haley approves of her new hammock 🐭 #ratsofinstagram... ---
  CoT Length : 90 words
  Crit.Tokens: ['genuinely', 'Step', 'Haley', 'approval', 'hamm']
  RoBERTa=0.187 | CoT=0.5 | α=0.550 | Fused=0.328 | Pred=0 | True=0 | ✅

--- Processing Tweet: 30 years on, people still haven't got justice they deserve. ... ---
  CoT Length : 10 words
  Crit.Tokens: ['RESP', 'dict']
  RoBERTa=0.915 | CoT=0.5 | α=0.550 | Fused=0.728 | Pred=1 | True=1 | ✅

--- Processing Tweet: Pips who drop out of school n have Kirya as 'eir role model ... ---
  CoT Length : 88 words
  Crit.Tokens: ['However', 'concludes', 'dict', 'ironic', 'providing']
  RoBERTa=0.289 | CoT=0.0 | α=0.550 | Fused=0.159 | Pred=0 | True=0 | ✅

--- Processing Tweet: Free Pets and Animals Books #freebiebookdownload #Pets... ---
  CoT Length : 91 words
  Crit.Tokens: ['download', 'Reach', 'Step', 'offer', 'helpful']
  RoBERTa=0.155 | CoT=0.5 | α=0.550 | Fused=0.310 | Pred=0 | True=0 | ✅

--- Processing Tweet: @user There will be no next employer in NFL for Trestman. He... ---
  CoT Length : 89 words
  Crit.Tokens: ['irony', 'contradiction', 'Consider', 'express', 'hires']
  RoBERTa=0.081 | CoT=0.5 | α=0.550 | Fused=0.269 | Pred=0 | True=0 | ✅

--- Processing Tweet: Loooovvveeeeeee when my phone gets wiped -.- #not... ---
  CoT Length : 80 words
  Crit.Tokens: ['contradictory', 'Analysis', 'Interpret', 'suggests', 'However']
  RoBERTa=0.306 | CoT=0.5 | α=0.550 | Fused=0.394 | Pred=0 | True=1 | ❌

--- Processing Tweet: Painting all cops with a broad brush because of the actions ... ---
  CoT Length : 99 words
  Crit.Tokens: ['Painting', 'straightforward', 'explicitly', 'painting', 'situations']
  RoBERTa=0.861 | CoT=0.5 | α=0.550 | Fused=0.699 | Pred=1 | True=1 | ✅

--- Processing Tweet: Don't know if I can handle this crazy 11-2 shift. It's so lo... ---
  CoT Length : 87 words
  Crit.Tokens: ['ironic', 'dict', 'However', 'context', 'This']
  RoBERTa=0.084 | CoT=1.0 | α=0.550 | Fused=0.496 | Pred=0 | True=1 | ❌

--- Processing Tweet: I just love being ignored😊|#not😒... ---
  CoT Length : 89 words
  Crit.Tokens: ['There', 'Step', 'contradiction', 'Being', 'underlying']
  RoBERTa=0.180 | CoT=0.5 | α=0.550 | Fused=0.324 | Pred=0 | True=1 | ❌

--- Processing Tweet: #Irony RT @user If you're going to give someone a scathing, ... ---
  CoT Length : 90 words
  Crit.Tokens: ['Step', 'ironic', 'irony', 'Consider', 'Eval']
  RoBERTa=0.295 | CoT=0.5 | α=0.550 | Fused=0.387 | Pred=0 | True=1 | ❌

--- Processing Tweet: Produce Mobile Apps #not... ---
  CoT Length : 94 words
  Crit.Tokens: ['Produ', 'Step', 'humorous', 'ironic', 'Mobile']
  RoBERTa=0.319 | CoT=0.5 | α=0.550 | Fused=0.400 | Pred=0 | True=1 | ❌

--- Processing Tweet: Decide that you want it more than you are afraid of it. -Bil... ---
  CoT Length : 59 words
  Crit.Tokens: ['dict', 'Cosby', 'motivational', 'ironic', 'desires']
  RoBERTa=0.077 | CoT=0.0 | α=0.550 | Fused=0.042 | Pred=0 | True=1 | ❌

--- Processing Tweet: Finally finished the first season of #VeronicaMars. Move ove... ---
  CoT Length : 79 words
  Crit.Tokens: ['ultimate', 'sheriff', 'irony', 'statement', 'Ident']
  RoBERTa=0.103 | CoT=1.0 | α=0.550 | Fused=0.507 | Pred=1 | True=0 | ❌

--- Processing Tweet: Merry Christmas to all those soldiers out there that couldn'... ---
  CoT Length : 90 words
  Crit.Tokens: ['dict', 'Christmas', 'context', 'contrast', 'However']
  RoBERTa=0.041 | CoT=1.0 | α=0.550 | Fused=0.472 | Pred=0 | True=0 | ✅

--- Processing Tweet: About as relevant as Michael Sam and Jason Collins. RT @user... ---
  CoT Length : 102 words
  Crit.Tokens: ['Therefore', 'observation', 'significant', 'tweet', 'appears']
  RoBERTa=0.788 | CoT=0.5 | α=0.550 | Fused=0.658 | Pred=1 | True=0 | ❌

--- Processing Tweet: Getting Final Jeopardy correct on Kids Jeopardy boosts my se... ---
  CoT Length : 92 words
  Crit.Tokens: ['dict', 'esteem', 'ironic', 'opard', 'absurdity']
  RoBERTa=0.966 | CoT=1.0 | α=0.550 | Fused=0.981 | Pred=1 | True=0 | ❌

--- Processing Tweet: itsfunny bc people think im quiet|but im just listening toev... ---
  CoT Length : 94 words
  Crit.Tokens: ['exaggerated', 'align', 'Step', 'Consider', 'hashtag']
  RoBERTa=0.093 | CoT=0.5 | α=0.550 | Fused=0.276 | Pred=0 | True=1 | ❌

--- Processing Tweet: Woke Up , showered , made a lunch and got ready for work onl... ---
  CoT Length : 64 words
  Crit.Tokens: ['dict', 'realization', 'RESP', 'recount', 'surprise']
  RoBERTa=0.603 | CoT=0.0 | α=0.550 | Fused=0.332 | Pred=0 | True=0 | ✅

--- Processing Tweet: @user @user @user @user @user How many of those jobs earn #m... ---
  CoT Length : 89 words
  Crit.Tokens: ['dict', 'earnings', 'Consider', 'QUEST', 'irony']
  RoBERTa=0.096 | CoT=1.0 | α=0.550 | Fused=0.503 | Pred=1 | True=0 | ❌

--- Processing Tweet: I reckon straight women fancy victoria secret models more th... ---
  CoT Length : 97 words
  Crit.Tokens: ['Eval', 'observation', 'Step', 'Consider', 'uate']
  RoBERTa=0.879 | CoT=0.5 | α=0.550 | Fused=0.708 | Pred=1 | True=1 | ✅

--- Processing Tweet: Incredible insight on the @user #bornrisky campaign: #ampute... ---
  CoT Length : 81 words
  Crit.Tokens: ['indication', 'contradiction', 'dict', 'irony', 'tones']
  RoBERTa=0.311 | CoT=1.0 | α=0.550 | Fused=0.621 | Pred=1 | True=0 | ❌

--- Processing Tweet: Love #hiphop mix tapes or have a mixtape to promote check ou... ---
  CoT Length : 91 words
  Crit.Tokens: ['There', 'advertisement', 'Step', 'contradiction', 'invitation']
  RoBERTa=0.057 | CoT=0.5 | α=0.550 | Fused=0.256 | Pred=0 | True=0 | ✅

--- Processing Tweet: Extended cut "NICHA" #trailer #spoof #film #dramatic #action... ---
  CoT Length : 76 words
  Crit.Tokens: ['refers', 'amine', 'dict', 'Step', '2014']
  RoBERTa=0.210 | CoT=1.0 | α=0.550 | Fused=0.566 | Pred=1 | True=0 | ❌

--- Processing Tweet: @user Stunning work. #british #textiles #footwear #madeinbri... ---
  CoT Length : 86 words
  Crit.Tokens: ['Step', 'congratulations', 'indicators', 'related', 'congrat']

,Tweet,True,Pred,✓?,RoBERTa P(ironic),CoT Verdict,α (adaptive),Fused P(ironic),Entropy,Gamma,Orig Len,Comp Len,Critical Tokens
0,@user Can U Help?||More conservativ...,0,0,✅,0.303,0.5,0.55,0.392,0.0,0.5,61,30,"['PROG', 'difference', 'groups', 'make', 'doing']"
1,Just walked in to #Starbucks and as...,1,1,✅,0.650,1.0,0.55,0.807,0.0,0.5,92,46,"['expresses', 'dict', 'nonsensical', 'ironic',..."
2,#NOT GONNA WIN...,0,0,✅,0.033,0.5,0.55,0.243,0.0,0.5,96,48,"['their', 'Step', 'hashtag', 'feelings', 'happy']"
3,@user He is exactly that sort of pe...,0,0,✅,0.209,0.5,0.55,0.340,0.0,0.5,94,47,"['Analysis', 'Context', 'general', 'Content', ..."
4,So much #sarcasm at work mate 10/10...,1,0,❌,0.075,1.0,0.55,0.491,0.0,0.5,79,39,"['work', 'ironic', 'acknowledging', 'atmospher..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,The last day of the year and I will...,0,1,❌,0.133,1.0,0.55,0.523,0.0,0.5,86,43,"['dict', 'contradiction', 'immediately', 'Step..."
96,MB forgot to move the elf on shelf ...,0,1,❌,0.629,1.0,0.55,0.796,0.0,0.5,80,40,"['hearted', 'described', 'disbelief', 'light',..."
97,"@user happy new year, da! Thanks so...",0,0,✅,0.095,0.5,0.55,0.278,0.0,0.5,96,48,"['There', 'meanings', 'hidden', 'Consider', 'S..."
98,WATCH: #Megatron from #Transformers...,0,1,❌,0.515,1.0,0.55,0.733,0.0,0.5,79,39,"['dict', 'indication', 'implying', 'ironic', '..."
99,@user @user #not #working when are ...,0,0,✅,0.075,1.0,0.55,0.491,0.0,0.5,88,44,"['expressing', 'Step', 'irony', 'genuine', 'di..."